-- Technical prelude generated by PHASE-03.
DO $$
BEGIN
  IF current_database() <> 'sjg_oms' THEN
    RAISE EXCEPTION 'PHASE-03 migration expected database sjg_oms, got %', current_database();
  END IF;
END
$$;

-- PHASE-03 database ownership guard.
-- A bootstrap superuser may normalize a newly created target database to sjg_owner.
-- Non-superuser migration execution requires the database to already be owned by sjg_owner.
DO $$
DECLARE
  v_owner text;
  v_is_superuser boolean := current_setting('is_superuser')::boolean;
BEGIN
  SELECT pg_get_userbyid(datdba) INTO v_owner
  FROM pg_database
  WHERE datname = current_database();

  IF v_owner IS DISTINCT FROM 'sjg_owner' THEN
    IF v_is_superuser THEN
      EXECUTE format('ALTER DATABASE %I OWNER TO sjg_owner', current_database());
    ELSE
      RAISE EXCEPTION 'database % must be owned by sjg_owner before sjg_migration executes; current owner=%',
        current_database(), v_owner;
    END IF;
  END IF;
END
$$;

SET ROLE sjg_owner;
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE sjg_oms TO sjg_owner;
GRANT CONNECT ON DATABASE sjg_oms TO sjg_migration;
GRANT CONNECT ON DATABASE sjg_oms TO sjg_api_runtime;
GRANT CONNECT ON DATABASE sjg_oms TO sjg_worker_runtime;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
RESET ROLE;
-- Runtime principals (sjg_api_runtime, sjg_worker_runtime) receive schema/table privileges only in the post-grant migration.
