-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/11_content_tables.sql
-- source_sha256: e884ccd0079d4445f986b97a52b9bbc95645a3ea0c49a227aafb6848134136d8
SET ROLE sjg_owner;
-- Schema: content / 企宣内容
SET search_path TO content, public;

-- 内容返工变更主表: 承载返工变更的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS content.change_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    content_asset_no varchar(64) NOT NULL,
    content_title varchar(200) NOT NULL,
    content_type varchar(64) NOT NULL,
    copyright_info text,
    expected_effective_at timestamptz,
    known_impact text,
    planned_publish_at timestamptz,
    review_points text,
    script_copy text
);
COMMENT ON TABLE content.change_request IS '内容返工变更主表｜承载返工变更的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN content.change_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN content.change_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN content.change_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN content.change_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN content.change_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.content_asset_no IS '内容/物料编号｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.content_title IS '主题/标题｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.content_type IS '内容类型｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.copyright_info IS '版权授权信息｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.planned_publish_at IS '计划发布时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.review_points IS '品牌/事实审核要点｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request.script_copy IS '脚本/文案｜敏感级别:P1-内部';

-- 内容返工变更明细项: 按field_code承载：after_snapshot、before_snapshot、media_metrics、publish_channels
CREATE TABLE IF NOT EXISTS content.change_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE content.change_request_item IS '内容返工变更明细项｜按field_code承载：after_snapshot、before_snapshot、media_metrics、publish_channels';
COMMENT ON COLUMN content.change_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN content.change_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN content.change_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 宣传物料制作主表: 承载宣传物料制作的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS content.material_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    content_asset_no varchar(64) NOT NULL,
    content_title varchar(200) NOT NULL,
    content_type varchar(64) NOT NULL,
    copyright_info text,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    planned_publish_at timestamptz,
    review_points text,
    script_copy text
);
COMMENT ON TABLE content.material_request IS '宣传物料制作主表｜承载宣传物料制作的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN content.material_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN content.material_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN content.material_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN content.material_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN content.material_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.content_asset_no IS '内容/物料编号｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.content_title IS '主题/标题｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.content_type IS '内容类型｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.copyright_info IS '版权授权信息｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.planned_publish_at IS '计划发布时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.review_points IS '品牌/事实审核要点｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request.script_copy IS '脚本/文案｜敏感级别:P1-内部';

-- 宣传物料制作明细项: 按field_code承载：media_metrics、publish_channels
CREATE TABLE IF NOT EXISTS content.material_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE content.material_request_item IS '宣传物料制作明细项｜按field_code承载：media_metrics、publish_channels';
COMMENT ON COLUMN content.material_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN content.material_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN content.material_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 拍摄任务主表: 承载拍摄任务的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS content.shooting_task (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    content_asset_no varchar(64) NOT NULL,
    content_title varchar(200) NOT NULL,
    content_type varchar(64) NOT NULL,
    copyright_info text,
    planned_publish_at timestamptz,
    review_points text,
    script_copy text
);
COMMENT ON TABLE content.shooting_task IS '拍摄任务主表｜承载拍摄任务的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN content.shooting_task.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN content.shooting_task.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN content.shooting_task.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN content.shooting_task.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN content.shooting_task.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.content_asset_no IS '内容/物料编号｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.content_title IS '主题/标题｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.content_type IS '内容类型｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.copyright_info IS '版权授权信息｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.planned_publish_at IS '计划发布时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.review_points IS '品牌/事实审核要点｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task.script_copy IS '脚本/文案｜敏感级别:P1-内部';

-- 拍摄任务明细项: 按field_code承载：media_metrics、publish_channels
CREATE TABLE IF NOT EXISTS content.shooting_task_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE content.shooting_task_item IS '拍摄任务明细项｜按field_code承载：media_metrics、publish_channels';
COMMENT ON COLUMN content.shooting_task_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN content.shooting_task_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN content.shooting_task_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
