-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/13_costume_tables.sql
-- source_sha256: 76cb085469bc27d40655d05606a88c106e3f9f18687dc6a1aae2f4017ac329ca
SET ROLE sjg_owner;
-- Schema: costume / 服化道
SET search_path TO costume, public;

-- 服化道报损主表: 承载损坏报损的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS costume.damage_report (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    asset_condition varchar(64),
    batch_serial_no varchar(128),
    book_value numeric(18,2),
    custodian_id varchar(32),
    fault_location_env varchar(200),
    fault_object varchar(200) NOT NULL,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    spec_model varchar(200),
    stock_quantity numeric(18,6) NOT NULL,
    unit varchar(64) NOT NULL,
    warehouse_location_id varchar(64) NOT NULL
);
COMMENT ON TABLE costume.damage_report IS '服化道报损主表｜承载损坏报损的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN costume.damage_report.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN costume.damage_report.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN costume.damage_report.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN costume.damage_report.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN costume.damage_report.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.asset_condition IS '状态/成色｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.batch_serial_no IS '批次/序列号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.book_value IS '账面价值｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN costume.damage_report.custodian_id IS '责任人/领用人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.fault_location_env IS '发生地点/环境｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.fault_object IS '故障/请求对象｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.stock_quantity IS '数量｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN costume.damage_report.unit IS '单位｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.damage_report.warehouse_location_id IS '仓库/存放位置｜敏感级别:P1-内部';

-- 服化道盘点主表: 承载盘点的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS costume.inventory_check (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    asset_condition varchar(64),
    batch_serial_no varchar(128),
    book_value numeric(18,2),
    custodian_id varchar(32),
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    program_version_id varchar(64) NOT NULL,
    show_session_no varchar(64),
    spec_model varchar(200),
    stock_quantity numeric(18,6) NOT NULL,
    unit varchar(64) NOT NULL,
    warehouse_location_id varchar(64) NOT NULL
);
COMMENT ON TABLE costume.inventory_check IS '服化道盘点主表｜承载盘点的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN costume.inventory_check.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN costume.inventory_check.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN costume.inventory_check.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN costume.inventory_check.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN costume.inventory_check.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.asset_condition IS '状态/成色｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.batch_serial_no IS '批次/序列号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.book_value IS '账面价值｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN costume.inventory_check.custodian_id IS '责任人/领用人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.program_version_id IS '节目编号/版本｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.show_session_no IS '场次编号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.stock_quantity IS '数量｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN costume.inventory_check.unit IS '单位｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.inventory_check.warehouse_location_id IS '仓库/存放位置｜敏感级别:P1-内部';

-- 服化道场次准备主表: 承载场次准备的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS costume.session_preparation (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    audience_summary text,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    pre_show_check varchar(64),
    program_version_id varchar(64) NOT NULL,
    role_position varchar(100),
    show_result varchar(64),
    show_session_no varchar(64),
    show_time timestamptz,
    show_venue_id varchar(64)
);
COMMENT ON TABLE costume.session_preparation IS '服化道场次准备主表｜承载场次准备的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN costume.session_preparation.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN costume.session_preparation.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN costume.session_preparation.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN costume.session_preparation.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN costume.session_preparation.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.audience_summary IS '观众/客流摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.pre_show_check IS '场前检查结果｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.program_version_id IS '节目编号/版本｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.role_position IS '角色/岗位｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.show_result IS '演出结果｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.show_session_no IS '场次编号｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.show_time IS '演出日期时间｜敏感级别:P1-内部';
COMMENT ON COLUMN costume.session_preparation.show_venue_id IS '演出场地｜敏感级别:P1-内部';
RESET ROLE;
