-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/18_drone_tables.sql
-- source_sha256: 49a05a0a726ee89b2aab29bdf6f9f4cce6b2feea5f1f67dc7163c4848c56a89b
SET ROLE sjg_owner;
-- Schema: drone / 无人机
SET search_path TO drone, public;

-- 飞行取消主表: 承载任务取消的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS drone.flight_cancellation (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    drone_asset_id varchar(64) NOT NULL,
    filing_permit_no varchar(128),
    flight_area text NOT NULL,
    flight_purpose varchar(64) NOT NULL,
    flight_task_no varchar(64) NOT NULL,
    order_no varchar(64) NOT NULL,
    pilot_id varchar(32) NOT NULL,
    pilot_license_no varchar(64) NOT NULL,
    planned_flight_window tstzrange NOT NULL,
    sales_channel varchar(64) NOT NULL
);
COMMENT ON TABLE drone.flight_cancellation IS '飞行取消主表｜承载任务取消的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN drone.flight_cancellation.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN drone.flight_cancellation.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN drone.flight_cancellation.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN drone.flight_cancellation.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN drone.flight_cancellation.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.drone_asset_id IS '飞行器编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.filing_permit_no IS '报备/许可编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.flight_area IS '飞行区域/空域｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.flight_purpose IS '飞行用途｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.flight_task_no IS '飞行任务编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.order_no IS '订单编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.pilot_id IS '飞行员｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.pilot_license_no IS '资质证书编号｜敏感级别:P2-个人';
COMMENT ON COLUMN drone.flight_cancellation.planned_flight_window IS '计划起止时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation.sales_channel IS '销售渠道｜敏感级别:P1-内部';

-- 飞行取消明细项: 按field_code承载：flight_log、weather_condition
CREATE TABLE IF NOT EXISTS drone.flight_cancellation_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE drone.flight_cancellation_item IS '飞行取消明细项｜按field_code承载：flight_log、weather_condition';
COMMENT ON COLUMN drone.flight_cancellation_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN drone.flight_cancellation_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_cancellation_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 飞行事故主表: 承载飞行事故的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS drone.flight_incident (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    drone_asset_id varchar(64) NOT NULL,
    filing_permit_no varchar(128),
    flight_area text NOT NULL,
    flight_purpose varchar(64) NOT NULL,
    flight_task_no varchar(64) NOT NULL,
    logistics_resource_type varchar(64) NOT NULL,
    pilot_id varchar(32) NOT NULL,
    pilot_license_no varchar(64) NOT NULL,
    planned_flight_window tstzrange NOT NULL,
    resource_no varchar(64) NOT NULL
);
COMMENT ON TABLE drone.flight_incident IS '飞行事故主表｜承载飞行事故的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN drone.flight_incident.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN drone.flight_incident.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN drone.flight_incident.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN drone.flight_incident.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN drone.flight_incident.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.drone_asset_id IS '飞行器编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.filing_permit_no IS '报备/许可编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.flight_area IS '飞行区域/空域｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.flight_purpose IS '飞行用途｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.flight_task_no IS '飞行任务编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.logistics_resource_type IS '资源类型｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.pilot_id IS '飞行员｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.pilot_license_no IS '资质证书编号｜敏感级别:P2-个人';
COMMENT ON COLUMN drone.flight_incident.planned_flight_window IS '计划起止时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident.resource_no IS '车辆/房间/床位编号｜敏感级别:P1-内部';

-- 飞行事故明细项: 按field_code承载：flight_log、weather_condition
CREATE TABLE IF NOT EXISTS drone.flight_incident_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE drone.flight_incident_item IS '飞行事故明细项｜按field_code承载：flight_log、weather_condition';
COMMENT ON COLUMN drone.flight_incident_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN drone.flight_incident_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_incident_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 无人机飞行任务主表: 承载飞行任务的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS drone.flight_task (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    drone_asset_id varchar(64) NOT NULL,
    filing_permit_no varchar(128),
    flight_area text NOT NULL,
    flight_purpose varchar(64) NOT NULL,
    flight_task_no varchar(64) NOT NULL,
    pilot_id varchar(32) NOT NULL,
    pilot_license_no varchar(64) NOT NULL,
    planned_flight_window tstzrange NOT NULL
);
COMMENT ON TABLE drone.flight_task IS '无人机飞行任务主表｜承载飞行任务的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN drone.flight_task.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN drone.flight_task.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN drone.flight_task.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN drone.flight_task.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN drone.flight_task.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.drone_asset_id IS '飞行器编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.filing_permit_no IS '报备/许可编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.flight_area IS '飞行区域/空域｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.flight_purpose IS '飞行用途｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.flight_task_no IS '飞行任务编号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.pilot_id IS '飞行员｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task.pilot_license_no IS '资质证书编号｜敏感级别:P2-个人';
COMMENT ON COLUMN drone.flight_task.planned_flight_window IS '计划起止时间｜敏感级别:P1-内部';

-- 无人机飞行任务明细项: 按field_code承载：flight_log、weather_condition
CREATE TABLE IF NOT EXISTS drone.flight_task_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE drone.flight_task_item IS '无人机飞行任务明细项｜按field_code承载：flight_log、weather_condition';
COMMENT ON COLUMN drone.flight_task_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN drone.flight_task_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN drone.flight_task_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
