-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/20_education_tables.sql
-- source_sha256: 8e34b5708578065bbea8f8a47bb3a3693e80c6d785aa23c77cd7f97990db1615
SET ROLE sjg_owner;
-- Schema: education / 教育研学
SET search_path TO education, public;

-- 课程产品主表: 承载课程产品上线的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS education.course_product (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    class_location varchar(200),
    class_time timestamptz,
    course_evaluation numeric(18,6),
    course_team_name varchar(200) NOT NULL,
    course_version_id varchar(64) NOT NULL,
    learner_profile varchar(500),
    period_or_course_no varchar(32) NOT NULL,
    safety_requirements text,
    teaching_record text,
    team_size bigint
);
COMMENT ON TABLE education.course_product IS '课程产品主表｜承载课程产品上线的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN education.course_product.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN education.course_product.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN education.course_product.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN education.course_product.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN education.course_product.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.class_location IS '上课地点｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.class_time IS '上课时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.course_evaluation IS '课程评价｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.course_team_name IS '课程/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.course_version_id IS '课程编号/版本｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.learner_profile IS '适用年龄/对象｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.period_or_course_no IS '周期/课程编号｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.safety_requirements IS '安全与应急要求｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.teaching_record IS '教学/实操记录｜敏感级别:P1-内部';
COMMENT ON COLUMN education.course_product.team_size IS '团队人数｜敏感级别:P1-内部';

-- 研学团队交付主表: 承载研学团队交付的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS education.study_tour_delivery (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    budget_item_id varchar(32),
    class_location varchar(200),
    class_time timestamptz,
    cost_center_id varchar(32) NOT NULL,
    course_evaluation numeric(18,6),
    course_team_name varchar(200) NOT NULL,
    course_version_id varchar(64) NOT NULL,
    learner_profile varchar(500),
    safety_requirements text,
    teaching_record text,
    team_size bigint
);
COMMENT ON TABLE education.study_tour_delivery IS '研学团队交付主表｜承载研学团队交付的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN education.study_tour_delivery.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN education.study_tour_delivery.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN education.study_tour_delivery.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN education.study_tour_delivery.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN education.study_tour_delivery.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.class_location IS '上课地点｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.class_time IS '上课时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.course_evaluation IS '课程评价｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.course_team_name IS '课程/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.course_version_id IS '课程编号/版本｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.learner_profile IS '适用年龄/对象｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.safety_requirements IS '安全与应急要求｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.teaching_record IS '教学/实操记录｜敏感级别:P1-内部';
COMMENT ON COLUMN education.study_tour_delivery.team_size IS '团队人数｜敏感级别:P1-内部';

-- 讲师排课主表: 承载讲师排课的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS education.teacher_schedule (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    class_location varchar(200),
    class_time timestamptz,
    course_evaluation numeric(18,6),
    course_team_name varchar(200) NOT NULL,
    course_version_id varchar(64) NOT NULL,
    expected_effective_at timestamptz,
    known_impact text,
    learner_profile varchar(500),
    period_or_course_no varchar(32) NOT NULL,
    safety_requirements text,
    teaching_record text,
    team_size bigint
);
COMMENT ON TABLE education.teacher_schedule IS '讲师排课主表｜承载讲师排课的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN education.teacher_schedule.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN education.teacher_schedule.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN education.teacher_schedule.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN education.teacher_schedule.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN education.teacher_schedule.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.class_location IS '上课地点｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.class_time IS '上课时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.course_evaluation IS '课程评价｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.course_team_name IS '课程/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.course_version_id IS '课程编号/版本｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.learner_profile IS '适用年龄/对象｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.period_or_course_no IS '周期/课程编号｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.safety_requirements IS '安全与应急要求｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.teaching_record IS '教学/实操记录｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule.team_size IS '团队人数｜敏感级别:P1-内部';

-- 讲师排课明细项: 按field_code承载：after_snapshot、before_snapshot
CREATE TABLE IF NOT EXISTS education.teacher_schedule_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE education.teacher_schedule_item IS '讲师排课明细项｜按field_code承载：after_snapshot、before_snapshot';
COMMENT ON COLUMN education.teacher_schedule_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN education.teacher_schedule_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN education.teacher_schedule_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
