-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/22_finance_tables.sql
-- source_sha256: 34082cd1797eec17c828b909142ce84337483c0f39beab6ebb263aebda348cdc
SET ROLE sjg_owner;
-- Schema: finance / 财务管理
SET search_path TO finance, public;

-- 预算申请主表: 承载预算闭环的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS finance.budget_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    approved_amount numeric(18,2),
    budget_item_id varchar(32),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    cost_center_id varchar(32) NOT NULL,
    counterparty_name varchar(200),
    currency varchar(64) NOT NULL,
    expected_effective_at timestamptz,
    invoice_verification varchar(64),
    known_impact text,
    payment_status varchar(64),
    requested_amount numeric(18,2),
    voucher_no varchar(64)
);
COMMENT ON TABLE finance.budget_request IS '预算申请主表｜承载预算闭环的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN finance.budget_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.budget_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN finance.budget_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN finance.budget_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN finance.budget_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.approved_amount IS '核定金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.budget_request.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.counterparty_name IS '收付款对象｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.currency IS '币种｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.invoice_verification IS '票据验真结果｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.payment_status IS '付款/回款状态｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request.requested_amount IS '申请/业务金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.budget_request.voucher_no IS '凭证编号｜敏感级别:P1-内部';

-- 预算申请明细项: 按field_code承载：after_snapshot、before_snapshot、invoice_nos
CREATE TABLE IF NOT EXISTS finance.budget_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE finance.budget_request_item IS '预算申请明细项｜按field_code承载：after_snapshot、before_snapshot、invoice_nos';
COMMENT ON COLUMN finance.budget_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.budget_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.budget_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 报销单主表: 承载报销闭环的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS finance.expense_claim (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    approved_amount numeric(18,2),
    budget_item_id varchar(32),
    cost_center_id varchar(32) NOT NULL,
    counterparty_name varchar(200),
    currency varchar(64) NOT NULL,
    invoice_verification varchar(64),
    payment_status varchar(64),
    requested_amount numeric(18,2),
    voucher_no varchar(64)
);
COMMENT ON TABLE finance.expense_claim IS '报销单主表｜承载报销闭环的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN finance.expense_claim.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.expense_claim.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN finance.expense_claim.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN finance.expense_claim.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN finance.expense_claim.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.approved_amount IS '核定金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.expense_claim.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.counterparty_name IS '收付款对象｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.currency IS '币种｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.invoice_verification IS '票据验真结果｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.payment_status IS '付款/回款状态｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim.requested_amount IS '申请/业务金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.expense_claim.voucher_no IS '凭证编号｜敏感级别:P1-内部';

-- 报销单明细项: 按field_code承载：invoice_nos
CREATE TABLE IF NOT EXISTS finance.expense_claim_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE finance.expense_claim_item IS '报销单明细项｜按field_code承载：invoice_nos';
COMMENT ON COLUMN finance.expense_claim_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.expense_claim_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.expense_claim_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 借款核销主表: 承载借款核销的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS finance.loan_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    approved_amount numeric(18,2),
    budget_item_id varchar(32),
    cost_center_id varchar(32) NOT NULL,
    counterparty_name varchar(200),
    currency varchar(64) NOT NULL,
    invoice_verification varchar(64),
    order_no varchar(64) NOT NULL,
    payment_status varchar(64),
    requested_amount numeric(18,2),
    sales_channel varchar(64) NOT NULL,
    voucher_no varchar(64)
);
COMMENT ON TABLE finance.loan_request IS '借款核销主表｜承载借款核销的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN finance.loan_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.loan_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN finance.loan_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN finance.loan_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN finance.loan_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.approved_amount IS '核定金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.loan_request.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.counterparty_name IS '收付款对象｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.currency IS '币种｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.invoice_verification IS '票据验真结果｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.order_no IS '订单编号｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.payment_status IS '付款/回款状态｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.requested_amount IS '申请/业务金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.loan_request.sales_channel IS '销售渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request.voucher_no IS '凭证编号｜敏感级别:P1-内部';

-- 借款核销明细项: 按field_code承载：invoice_nos
CREATE TABLE IF NOT EXISTS finance.loan_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE finance.loan_request_item IS '借款核销明细项｜按field_code承载：invoice_nos';
COMMENT ON COLUMN finance.loan_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.loan_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.loan_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 对账任务主表: 承载跨系统对账的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS finance.reconciliation_task (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    approved_amount numeric(18,2),
    budget_item_id varchar(32),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    cost_center_id varchar(32) NOT NULL,
    counterparty_name varchar(200),
    currency varchar(64) NOT NULL,
    employee_event_type varchar(64) NOT NULL,
    expected_effective_at timestamptz,
    invoice_verification varchar(64),
    known_impact text,
    payment_status varchar(64),
    requested_amount numeric(18,2),
    voucher_no varchar(64)
);
COMMENT ON TABLE finance.reconciliation_task IS '对账任务主表｜承载跨系统对账的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN finance.reconciliation_task.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.reconciliation_task.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN finance.reconciliation_task.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN finance.reconciliation_task.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN finance.reconciliation_task.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.approved_amount IS '核定金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.reconciliation_task.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.counterparty_name IS '收付款对象｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.currency IS '币种｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.employee_event_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.invoice_verification IS '票据验真结果｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.payment_status IS '付款/回款状态｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task.requested_amount IS '申请/业务金额｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN finance.reconciliation_task.voucher_no IS '凭证编号｜敏感级别:P1-内部';

-- 对账任务明细项: 按field_code承载：after_snapshot、before_snapshot、invoice_nos
CREATE TABLE IF NOT EXISTS finance.reconciliation_task_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE finance.reconciliation_task_item IS '对账任务明细项｜按field_code承载：after_snapshot、before_snapshot、invoice_nos';
COMMENT ON COLUMN finance.reconciliation_task_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN finance.reconciliation_task_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN finance.reconciliation_task_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
