-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/23_fleet_tables.sql
-- source_sha256: 37f5022663874b307d60e37bdc03f3e0ddf83110112440a0b83655b3a3966fac
SET ROLE sjg_owner;
-- Schema: fleet / 车辆管理
SET search_path TO fleet, public;

-- 车辆派车主表: 承载派车的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS fleet.vehicle_dispatch (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    driver_id varchar(32),
    guest_team_name varchar(200) NOT NULL,
    logistics_resource_type varchar(64) NOT NULL,
    reception_level varchar(64) NOT NULL,
    reception_team_no varchar(64) NOT NULL,
    resource_no varchar(64) NOT NULL,
    resource_user_id varchar(32) NOT NULL,
    return_condition varchar(64),
    route_plan text,
    usage_metric numeric(18,6),
    use_end_at timestamptz,
    use_start_at timestamptz NOT NULL
);
COMMENT ON TABLE fleet.vehicle_dispatch IS '车辆派车主表｜承载派车的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN fleet.vehicle_dispatch.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN fleet.vehicle_dispatch.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN fleet.vehicle_dispatch.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN fleet.vehicle_dispatch.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN fleet.vehicle_dispatch.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.driver_id IS '驾驶员｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.guest_team_name IS '客户/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.logistics_resource_type IS '资源类型｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.reception_level IS '接待等级｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.reception_team_no IS '接待/团队编号｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.resource_no IS '车辆/房间/床位编号｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.resource_user_id IS '使用人/入住人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.return_condition IS '交付/归还状态｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.route_plan IS '行程/路线｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.usage_metric IS '里程/用量｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.use_end_at IS '使用结束时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_dispatch.use_start_at IS '使用开始时间｜敏感级别:P1-内部';

-- 车辆事故主表: 承载车辆事故的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS fleet.vehicle_incident (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    driver_id varchar(32),
    incident_area_id varchar(64) NOT NULL,
    incident_patrol_no varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    logistics_resource_type varchar(64) NOT NULL,
    resource_no varchar(64) NOT NULL,
    resource_user_id varchar(32) NOT NULL,
    return_condition varchar(64),
    route_plan text,
    usage_metric numeric(18,6),
    use_end_at timestamptz,
    use_start_at timestamptz NOT NULL
);
COMMENT ON TABLE fleet.vehicle_incident IS '车辆事故主表｜承载车辆事故的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN fleet.vehicle_incident.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN fleet.vehicle_incident.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN fleet.vehicle_incident.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN fleet.vehicle_incident.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN fleet.vehicle_incident.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.driver_id IS '驾驶员｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.incident_area_id IS '发生区域｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.logistics_resource_type IS '资源类型｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.resource_no IS '车辆/房间/床位编号｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.resource_user_id IS '使用人/入住人｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.return_condition IS '交付/归还状态｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.route_plan IS '行程/路线｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.usage_metric IS '里程/用量｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.use_end_at IS '使用结束时间｜敏感级别:P1-内部';
COMMENT ON COLUMN fleet.vehicle_incident.use_start_at IS '使用开始时间｜敏感级别:P1-内部';
RESET ROLE;
