-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/25_iam_tables.sql
-- source_sha256: 09fb210380d55efcda16f6e283e6969b24b75be0b4067ff8f925e5adcdb18192
SET ROLE sjg_owner;
-- Schema: iam / 身份权限
SET search_path TO iam, public;

-- 账号执行主表: 承载账号执行的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS iam.account_execution (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    environment varchar(64) NOT NULL,
    implementation_window tstzrange,
    person_no varchar(32) NOT NULL,
    rollback_plan text,
    system_service_name varchar(200) NOT NULL,
    tech_impact_scope text NOT NULL,
    tech_risk_level varchar(64) NOT NULL,
    tech_work_item_no varchar(64),
    verification_test_result text,
    version_build_no varchar(100)
);
COMMENT ON TABLE iam.account_execution IS '账号执行主表｜承载账号执行的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN iam.account_execution.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.account_execution.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN iam.account_execution.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN iam.account_execution.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN iam.account_execution.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.implementation_window IS '实施窗口｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.person_no IS '人员/候选人编号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.rollback_plan IS '回退方案｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.tech_impact_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.tech_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.tech_work_item_no IS '变更/需求/缺陷编号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.verification_test_result IS '健康检查/测试结果｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution.version_build_no IS '版本/构建号｜敏感级别:P1-内部';

-- 账号执行明细项: 按field_code承载：tech_logs_reports
CREATE TABLE IF NOT EXISTS iam.account_execution_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE iam.account_execution_item IS '账号执行明细项｜按field_code承载：tech_logs_reports';
COMMENT ON COLUMN iam.account_execution_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.account_execution_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.account_execution_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 数据权限规则表: 数据权限规则表
CREATE TABLE IF NOT EXISTS iam.data_scope_rule (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    scope_code varchar(64) NOT NULL,
    scope_name varchar(128) NOT NULL,
    rule_expr jsonb NOT NULL,
    sql_policy_name varchar(128),
    enabled boolean DEFAULT true NOT NULL
);
COMMENT ON TABLE iam.data_scope_rule IS '数据权限规则表｜数据权限规则表';
COMMENT ON COLUMN iam.data_scope_rule.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.data_scope_rule.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.scope_code IS '范围编码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.scope_name IS '范围名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.rule_expr IS '规则表达式｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.sql_policy_name IS 'RLS策略名｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.data_scope_rule.enabled IS '启用｜敏感级别:P1-内部';

-- 登录会话主表: 承载统一登录与多岗位身份切换的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS iam.login_session (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    actual_effective_date date,
    employment_type varchar(64) NOT NULL,
    headcount_no varchar(32),
    person_name varchar(50) NOT NULL,
    person_no varchar(32) NOT NULL,
    planned_effective_date date NOT NULL,
    salary_budget_range varchar(100),
    target_grade_id varchar(32),
    target_job_id varchar(32) NOT NULL
);
COMMENT ON TABLE iam.login_session IS '登录会话主表｜承载统一登录与多岗位身份切换的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN iam.login_session.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.login_session.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN iam.login_session.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN iam.login_session.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN iam.login_session.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.actual_effective_date IS '实际生效日期｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.employment_type IS '用工/任职类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.headcount_no IS '编制编号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.person_name IS '姓名｜敏感级别:P2-个人';
COMMENT ON COLUMN iam.login_session.person_no IS '人员/候选人编号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.planned_effective_date IS '计划生效日期｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.salary_budget_range IS '薪酬预算范围｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN iam.login_session.target_grade_id IS '职级/等级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session.target_job_id IS '目标岗位｜敏感级别:P1-内部';

-- 登录会话明细项: 按field_code承载：handover_checklist
CREATE TABLE IF NOT EXISTS iam.login_session_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE iam.login_session_item IS '登录会话明细项｜按field_code承载：handover_checklist';
COMMENT ON COLUMN iam.login_session_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.login_session_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.login_session_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 权限点表: 权限点表
CREATE TABLE IF NOT EXISTS iam.permission (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    permission_code varchar(128) NOT NULL,
    permission_name varchar(128) NOT NULL,
    resource_type varchar(32) NOT NULL,
    action_code varchar(32) NOT NULL,
    risk_level varchar(16) DEFAULT 'NORMAL' NOT NULL
);
COMMENT ON TABLE iam.permission IS '权限点表｜权限点表';
COMMENT ON COLUMN iam.permission.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.permission.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.permission_code IS '权限编码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.permission_name IS '权限名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.resource_type IS '资源类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.action_code IS '动作编码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission.risk_level IS '风险等级｜敏感级别:P1-内部';

-- 权限申请主表: 承载权限申请、复核与回收的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS iam.permission_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    actual_effective_date date,
    employee_event_type varchar(64) NOT NULL,
    employment_type varchar(64) NOT NULL,
    headcount_no varchar(32),
    person_name varchar(50) NOT NULL,
    person_no varchar(32) NOT NULL,
    planned_effective_date date NOT NULL,
    salary_budget_range varchar(100),
    target_grade_id varchar(32),
    target_job_id varchar(32) NOT NULL
);
COMMENT ON TABLE iam.permission_request IS '权限申请主表｜承载权限申请、复核与回收的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN iam.permission_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.permission_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN iam.permission_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN iam.permission_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN iam.permission_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.actual_effective_date IS '实际生效日期｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.employee_event_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.employment_type IS '用工/任职类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.headcount_no IS '编制编号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.person_name IS '姓名｜敏感级别:P2-个人';
COMMENT ON COLUMN iam.permission_request.person_no IS '人员/候选人编号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.planned_effective_date IS '计划生效日期｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.salary_budget_range IS '薪酬预算范围｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN iam.permission_request.target_grade_id IS '职级/等级｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request.target_job_id IS '目标岗位｜敏感级别:P1-内部';

-- 权限申请明细项: 按field_code承载：handover_checklist
CREATE TABLE IF NOT EXISTS iam.permission_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE iam.permission_request_item IS '权限申请明细项｜按field_code承载：handover_checklist';
COMMENT ON COLUMN iam.permission_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.permission_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.permission_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 角色表: 角色表
CREATE TABLE IF NOT EXISTS iam.role (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    role_code varchar(64) NOT NULL,
    role_name varchar(128) NOT NULL,
    role_type varchar(32) NOT NULL,
    data_scope_code varchar(64),
    enabled boolean DEFAULT true NOT NULL
);
COMMENT ON TABLE iam.role IS '角色表｜角色表';
COMMENT ON COLUMN iam.role.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.role.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.role_code IS '角色编码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.role_name IS '角色名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.role_type IS '角色类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.data_scope_code IS '数据范围代码｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role.enabled IS '启用｜敏感级别:P1-内部';

-- 角色权限表: 角色权限表
CREATE TABLE IF NOT EXISTS iam.role_permission (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    condition_expr jsonb
);
COMMENT ON TABLE iam.role_permission IS '角色权限表｜角色权限表';
COMMENT ON COLUMN iam.role_permission.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.role_permission.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.role_id IS '角色ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.permission_id IS '权限ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.role_permission.condition_expr IS '授权条件｜敏感级别:P1-内部';

-- 用户账户表: 用户账户表
CREATE TABLE IF NOT EXISTS iam.user_account (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    login_name varchar(128) NOT NULL,
    mobile_cipher bytea,
    mobile_hash varchar(128),
    email_cipher bytea,
    password_hash varchar(255),
    status varchar(32) DEFAULT 'ACTIVE' NOT NULL,
    last_login_at timestamptz,
    mfa_level smallint DEFAULT 0 NOT NULL
);
COMMENT ON TABLE iam.user_account IS '用户账户表｜用户账户表';
COMMENT ON COLUMN iam.user_account.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.user_account.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.login_name IS '登录名｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.mobile_cipher IS '手机号密文｜敏感级别:P2-个人';
COMMENT ON COLUMN iam.user_account.mobile_hash IS '手机号检索哈希｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.email_cipher IS '邮箱密文｜敏感级别:P2-个人';
COMMENT ON COLUMN iam.user_account.password_hash IS '密码哈希｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN iam.user_account.status IS '状态｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.last_login_at IS '最后登录｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_account.mfa_level IS 'MFA级别｜敏感级别:P1-内部';

-- 用户身份表: 用户身份表
CREATE TABLE IF NOT EXISTS iam.user_identity (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    user_id uuid NOT NULL,
    employee_id uuid,
    identity_type varchar(32) NOT NULL,
    identity_name varchar(128) NOT NULL,
    org_id uuid,
    position_id uuid,
    is_primary boolean DEFAULT false NOT NULL,
    effective_start_at timestamptz DEFAULT now() NOT NULL,
    effective_end_at timestamptz
);
COMMENT ON TABLE iam.user_identity IS '用户身份表｜用户身份表';
COMMENT ON COLUMN iam.user_identity.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.user_identity.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.user_id IS '用户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.employee_id IS '员工ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.identity_type IS '身份类型｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.identity_name IS '身份名称｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.org_id IS '组织ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.position_id IS '岗位ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.is_primary IS '是否主身份｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.effective_start_at IS '生效开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_identity.effective_end_at IS '生效结束｜敏感级别:P1-内部';

-- 用户角色表: 用户角色表
CREATE TABLE IF NOT EXISTS iam.user_role (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    user_id uuid NOT NULL,
    identity_id uuid,
    role_id uuid NOT NULL,
    effective_start_at timestamptz DEFAULT now() NOT NULL,
    effective_end_at timestamptz,
    grant_source varchar(32) NOT NULL
);
COMMENT ON TABLE iam.user_role IS '用户角色表｜用户角色表';
COMMENT ON COLUMN iam.user_role.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN iam.user_role.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.user_id IS '用户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.identity_id IS '身份ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.role_id IS '角色ID｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.effective_start_at IS '生效开始｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.effective_end_at IS '生效结束｜敏感级别:P1-内部';
COMMENT ON COLUMN iam.user_role.grant_source IS '授权来源｜敏感级别:P1-内部';
RESET ROLE;
