-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/26_integration_tables.sql
-- source_sha256: d120b00e5e0b787ea4bd44736af46f272e2e7d6b2f20f4c5391a0ba33079fd4a
SET ROLE sjg_owner;
-- Schema: integration / 集成平台
SET search_path TO integration, public;

-- 数据导入任务主表: 数据导入任务主表
CREATE TABLE IF NOT EXISTS integration.data_import_job (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    import_type varchar(64) NOT NULL,
    source_file_id uuid NOT NULL,
    template_version varchar(64) NOT NULL,
    total_rows integer DEFAULT 0 NOT NULL,
    success_rows integer DEFAULT 0 NOT NULL,
    failed_rows integer DEFAULT 0 NOT NULL,
    validation_result jsonb,
    result_file_id uuid,
    actual_amount numeric(18,2),
    actual_end_at timestamptz,
    actual_start_at timestamptz NOT NULL,
    business_date date NOT NULL,
    environment varchar(64) NOT NULL,
    implementation_window tstzrange,
    result_summary text NOT NULL,
    rollback_plan text,
    system_service_name varchar(200) NOT NULL,
    tech_impact_scope text NOT NULL,
    tech_risk_level varchar(64) NOT NULL,
    tech_work_item_no varchar(64),
    verification_test_result text,
    version_build_no varchar(100)
);
COMMENT ON TABLE integration.data_import_job IS '数据导入任务主表｜数据导入任务主表';
COMMENT ON COLUMN integration.data_import_job.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN integration.data_import_job.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN integration.data_import_job.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN integration.data_import_job.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN integration.data_import_job.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.import_type IS '导入类型｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.source_file_id IS '源文件ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.template_version IS '模板版本｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.total_rows IS '总行数｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.success_rows IS '成功行数｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.failed_rows IS '失败行数｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.validation_result IS '校验结果｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.result_file_id IS '结果文件ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.actual_end_at IS '实际结束时间｜敏感级别:P1-内部｜规则:不得早于开始时间';
COMMENT ON COLUMN integration.data_import_job.actual_start_at IS '实际开始时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.business_date IS '业务发生日期｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.implementation_window IS '实施窗口｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.rollback_plan IS '回退方案｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.tech_impact_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.tech_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.tech_work_item_no IS '变更/需求/缺陷编号｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.verification_test_result IS '健康检查/测试结果｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job.version_build_no IS '版本/构建号｜敏感级别:P1-内部';

-- 数据导入任务明细项: 按field_code承载：tech_logs_reports
CREATE TABLE IF NOT EXISTS integration.data_import_job_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE integration.data_import_job_item IS '数据导入任务明细项｜按field_code承载：tech_logs_reports';
COMMENT ON COLUMN integration.data_import_job_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN integration.data_import_job_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.data_import_job_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 死信表: 死信表
CREATE TABLE IF NOT EXISTS integration.dead_letter (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_type varchar(32) NOT NULL,
    source_id varchar(128) NOT NULL,
    payload jsonb NOT NULL,
    error_code varchar(64),
    error_message text,
    status varchar(32) DEFAULT 'OPEN' NOT NULL,
    resolved_at timestamptz
);
COMMENT ON TABLE integration.dead_letter IS '死信表｜死信表';
COMMENT ON COLUMN integration.dead_letter.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN integration.dead_letter.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.source_type IS '来源类型｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.source_id IS '来源ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.payload IS '载荷｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.error_code IS '错误码｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.error_message IS '错误信息｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.status IS '处理状态｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.dead_letter.resolved_at IS '解决时间｜敏感级别:P1-内部';

-- 集成端点表: 集成端点表
CREATE TABLE IF NOT EXISTS integration.endpoint (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    endpoint_code varchar(64) NOT NULL,
    system_name varchar(128) NOT NULL,
    protocol varchar(32) NOT NULL,
    endpoint_uri text NOT NULL,
    auth_type varchar(32) NOT NULL,
    timeout_ms integer DEFAULT 5000 NOT NULL,
    retry_policy jsonb,
    circuit_policy jsonb,
    enabled boolean DEFAULT true NOT NULL
);
COMMENT ON TABLE integration.endpoint IS '集成端点表｜集成端点表';
COMMENT ON COLUMN integration.endpoint.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN integration.endpoint.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.endpoint_code IS '端点编码｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.system_name IS '系统名称｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.protocol IS '协议｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.endpoint_uri IS '端点地址｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.auth_type IS '认证类型｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.timeout_ms IS '超时毫秒｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.retry_policy IS '重试策略｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.circuit_policy IS '熔断策略｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.endpoint.enabled IS '启用｜敏感级别:P1-内部';

-- 接口调用日志: 接口调用日志
CREATE TABLE IF NOT EXISTS integration.request_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    request_id varchar(128) NOT NULL,
    endpoint_id uuid NOT NULL,
    business_key varchar(128),
    request_summary jsonb,
    response_code varchar(64),
    duration_ms integer,
    success boolean NOT NULL,
    occurred_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE integration.request_log IS '接口调用日志｜接口调用日志';
COMMENT ON COLUMN integration.request_log.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN integration.request_log.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.request_id IS '请求ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.endpoint_id IS '端点ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.business_key IS '业务幂等键｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.request_summary IS '请求摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.response_code IS '响应码｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.duration_ms IS '耗时毫秒｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.success IS '成功｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.request_log.occurred_at IS '发生时间｜敏感级别:P1-内部';

-- 接口重试任务: 接口重试任务
CREATE TABLE IF NOT EXISTS integration.retry_task (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    request_id varchar(128) NOT NULL,
    endpoint_id uuid NOT NULL,
    payload jsonb NOT NULL,
    next_retry_at timestamptz NOT NULL,
    retry_count integer DEFAULT 0 NOT NULL,
    max_retries integer DEFAULT 3 NOT NULL,
    status varchar(32) DEFAULT 'PENDING' NOT NULL
);
COMMENT ON TABLE integration.retry_task IS '接口重试任务｜接口重试任务';
COMMENT ON COLUMN integration.retry_task.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN integration.retry_task.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.request_id IS '原请求ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.endpoint_id IS '端点ID｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.payload IS '重试载荷｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.next_retry_at IS '下次重试｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.retry_count IS '重试次数｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.max_retries IS '最大重试｜敏感级别:P1-内部';
COMMENT ON COLUMN integration.retry_task.status IS '状态｜敏感级别:P1-内部';
RESET ROLE;
