-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/27_itops_tables.sql
-- source_sha256: c2467c008f507d6cc98c7e3c7cec55c6721e105328cbbc2f9a597db6e032ca74
SET ROLE sjg_owner;
-- Schema: itops / IT运维
SET search_path TO itops, public;

-- 网络活动保障主表: 承载活动保障的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS itops.event_support (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    campaign_budget numeric(18,2),
    campaign_end_at timestamptz NOT NULL,
    campaign_goal text NOT NULL,
    campaign_location_channel varchar(500),
    campaign_name varchar(200) NOT NULL,
    campaign_no varchar(32) NOT NULL,
    campaign_start_at timestamptz NOT NULL,
    environment varchar(64) NOT NULL,
    system_service_name varchar(200) NOT NULL,
    target_audience_desc text,
    target_volume bigint
);
COMMENT ON TABLE itops.event_support IS '网络活动保障主表｜承载活动保障的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN itops.event_support.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.event_support.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN itops.event_support.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN itops.event_support.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN itops.event_support.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.campaign_budget IS '预算金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.campaign_end_at IS '结束时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.campaign_goal IS '活动目标｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.campaign_location_channel IS '活动地点/渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.campaign_name IS '活动名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.campaign_no IS '活动/项目编号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.campaign_start_at IS '开始时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.target_audience_desc IS '目标人群｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support.target_volume IS '目标线索/参与人数｜敏感级别:P1-内部';

-- 网络活动保障明细项: 按field_code承载：actual_metrics
CREATE TABLE IF NOT EXISTS itops.event_support_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE itops.event_support_item IS '网络活动保障明细项｜按field_code承载：actual_metrics';
COMMENT ON COLUMN itops.event_support_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.event_support_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.event_support_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 网络变更主表: 承载网络变更的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS itops.network_change (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    environment varchar(64) NOT NULL,
    expected_effective_at timestamptz,
    implementation_window tstzrange,
    incident_patrol_no varchar(64) NOT NULL,
    known_impact text,
    rollback_plan text,
    system_service_name varchar(200) NOT NULL,
    tech_impact_scope text NOT NULL,
    tech_risk_level varchar(64) NOT NULL,
    tech_work_item_no varchar(64),
    verification_test_result text,
    version_build_no varchar(100)
);
COMMENT ON TABLE itops.network_change IS '网络变更主表｜承载网络变更的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN itops.network_change.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.network_change.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN itops.network_change.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN itops.network_change.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN itops.network_change.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.implementation_window IS '实施窗口｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.rollback_plan IS '回退方案｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.tech_impact_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.tech_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.tech_work_item_no IS '变更/需求/缺陷编号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.verification_test_result IS '健康检查/测试结果｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change.version_build_no IS '版本/构建号｜敏感级别:P1-内部';

-- 网络变更明细项: 按field_code承载：after_snapshot、before_snapshot、tech_logs_reports
CREATE TABLE IF NOT EXISTS itops.network_change_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE itops.network_change_item IS '网络变更明细项｜按field_code承载：after_snapshot、before_snapshot、tech_logs_reports';
COMMENT ON COLUMN itops.network_change_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.network_change_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_change_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 网络故障主表: 承载网络故障的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS itops.network_incident (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    affected_scope text,
    business_interrupted boolean NOT NULL,
    diagnosis text,
    environment varchar(64) NOT NULL,
    fault_location_env varchar(200),
    fault_object varchar(200) NOT NULL,
    fault_symptom text NOT NULL,
    recovered_at timestamptz,
    resolution_action text,
    severity varchar(64) NOT NULL,
    system_service_name varchar(200) NOT NULL
);
COMMENT ON TABLE itops.network_incident IS '网络故障主表｜承载网络故障的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN itops.network_incident.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.network_incident.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN itops.network_incident.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN itops.network_incident.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN itops.network_incident.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.affected_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.business_interrupted IS '是否中断业务｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.diagnosis IS '诊断结果｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.fault_location_env IS '发生地点/环境｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.fault_object IS '故障/请求对象｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.fault_symptom IS '故障现象/服务请求｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.recovered_at IS '恢复时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.resolution_action IS '处理措施｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.severity IS '严重度｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';

-- 网络故障明细项: 按field_code承载：spare_parts
CREATE TABLE IF NOT EXISTS itops.network_incident_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE itops.network_incident_item IS '网络故障明细项｜按field_code承载：spare_parts';
COMMENT ON COLUMN itops.network_incident_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.network_incident_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.network_incident_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 恢复演练主表: 承载恢复演练的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS itops.recovery_drill (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    environment varchar(64) NOT NULL,
    implementation_window tstzrange,
    rollback_plan text,
    system_service_name varchar(200) NOT NULL,
    tech_impact_scope text NOT NULL,
    tech_risk_level varchar(64) NOT NULL,
    tech_work_item_no varchar(64),
    verification_test_result text,
    version_build_no varchar(100)
);
COMMENT ON TABLE itops.recovery_drill IS '恢复演练主表｜承载恢复演练的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN itops.recovery_drill.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.recovery_drill.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN itops.recovery_drill.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN itops.recovery_drill.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN itops.recovery_drill.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.implementation_window IS '实施窗口｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.rollback_plan IS '回退方案｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.tech_impact_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.tech_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.tech_work_item_no IS '变更/需求/缺陷编号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.verification_test_result IS '健康检查/测试结果｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill.version_build_no IS '版本/构建号｜敏感级别:P1-内部';

-- 恢复演练明细项: 按field_code承载：tech_logs_reports
CREATE TABLE IF NOT EXISTS itops.recovery_drill_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE itops.recovery_drill_item IS '恢复演练明细项｜按field_code承载：tech_logs_reports';
COMMENT ON COLUMN itops.recovery_drill_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.recovery_drill_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.recovery_drill_item.sort_no IS '排序｜敏感级别:P1-内部';

-- IT服务请求主表: 承载IT服务请求的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS itops.service_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    environment varchar(64) NOT NULL,
    fault_object varchar(200) NOT NULL,
    implementation_window tstzrange,
    rollback_plan text,
    system_service_name varchar(200) NOT NULL,
    tech_impact_scope text NOT NULL,
    tech_risk_level varchar(64) NOT NULL,
    tech_work_item_no varchar(64),
    verification_test_result text,
    version_build_no varchar(100)
);
COMMENT ON TABLE itops.service_request IS 'IT服务请求主表｜承载IT服务请求的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN itops.service_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.service_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN itops.service_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN itops.service_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN itops.service_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.fault_object IS '故障/请求对象｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.implementation_window IS '实施窗口｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.rollback_plan IS '回退方案｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.tech_impact_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.tech_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.tech_work_item_no IS '变更/需求/缺陷编号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.verification_test_result IS '健康检查/测试结果｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request.version_build_no IS '版本/构建号｜敏感级别:P1-内部';

-- IT服务请求明细项: 按field_code承载：tech_logs_reports
CREATE TABLE IF NOT EXISTS itops.service_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE itops.service_request_item IS 'IT服务请求明细项｜按field_code承载：tech_logs_reports';
COMMENT ON COLUMN itops.service_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN itops.service_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN itops.service_request_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
