-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/30_marketing_tables.sql
-- source_sha256: dd991c2d4d8fd11398e39e94668224f19b1f8c80d6190d4d93c737a890851346
SET ROLE sjg_owner;
-- Schema: marketing / 市场活动
SET search_path TO marketing, public;

-- 市场活动主表: 承载市场活动的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS marketing.campaign (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    budget_item_id varchar(32),
    campaign_budget numeric(18,2),
    campaign_end_at timestamptz NOT NULL,
    campaign_goal text NOT NULL,
    campaign_location_channel varchar(500),
    campaign_name varchar(200) NOT NULL,
    campaign_no varchar(32) NOT NULL,
    campaign_start_at timestamptz NOT NULL,
    cost_center_id varchar(32) NOT NULL,
    target_audience_desc text,
    target_volume bigint
);
COMMENT ON TABLE marketing.campaign IS '市场活动主表｜承载市场活动的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN marketing.campaign.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN marketing.campaign.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN marketing.campaign.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN marketing.campaign.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN marketing.campaign.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.campaign_budget IS '预算金额｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.campaign_end_at IS '结束时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.campaign_goal IS '活动目标｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.campaign_location_channel IS '活动地点/渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.campaign_name IS '活动名称｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.campaign_no IS '活动/项目编号｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.campaign_start_at IS '开始时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.target_audience_desc IS '目标人群｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign.target_volume IS '目标线索/参与人数｜敏感级别:P1-内部';

-- 市场活动明细项: 按field_code承载：actual_metrics
CREATE TABLE IF NOT EXISTS marketing.campaign_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE marketing.campaign_item IS '市场活动明细项｜按field_code承载：actual_metrics';
COMMENT ON COLUMN marketing.campaign_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN marketing.campaign_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN marketing.campaign_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
