-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/34_notification_tables.sql
-- source_sha256: b7633f764a2db4d1da3a8379994330c3fa4607e476669c9b43767ca43ee39b8f
SET ROLE sjg_owner;
-- Schema: notification / 消息通知
SET search_path TO notification, public;

-- 消息主表: 消息主表
CREATE TABLE IF NOT EXISTS notification.message (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    message_no varchar(64) NOT NULL,
    template_id uuid,
    recipient_type varchar(32) NOT NULL,
    recipient_id uuid,
    channel varchar(32) NOT NULL,
    title varchar(255),
    body text NOT NULL,
    status varchar(32) DEFAULT 'PENDING' NOT NULL,
    scheduled_at timestamptz,
    sent_at timestamptz
);
COMMENT ON TABLE notification.message IS '消息主表｜消息主表';
COMMENT ON COLUMN notification.message.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN notification.message.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.message_no IS '消息编号｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.template_id IS '模板ID｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.recipient_type IS '接收人类型｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.recipient_id IS '接收人ID｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.channel IS '渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.title IS '标题｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.body IS '正文｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.status IS '状态｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.scheduled_at IS '计划发送时间｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.message.sent_at IS '发送时间｜敏感级别:P1-内部';

-- 消息模板表: 消息模板表
CREATE TABLE IF NOT EXISTS notification.template (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    template_code varchar(64) NOT NULL,
    channel varchar(32) NOT NULL,
    title_template text,
    body_template text NOT NULL,
    variables_schema jsonb,
    enabled boolean DEFAULT true NOT NULL
);
COMMENT ON TABLE notification.template IS '消息模板表｜消息模板表';
COMMENT ON COLUMN notification.template.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN notification.template.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.template_code IS '模板编码｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.channel IS '渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.title_template IS '标题模板｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.body_template IS '正文模板｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.variables_schema IS '变量Schema｜敏感级别:P1-内部';
COMMENT ON COLUMN notification.template.enabled IS '启用｜敏感级别:P1-内部';
RESET ROLE;
