-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/35_org_tables.sql
-- source_sha256: fb669aff4e2628fdfe118c7b5feb13f8cd1160bb033c895b8845165ff2a9ff7e
SET ROLE sjg_owner;
-- Schema: org / 组织人员
SET search_path TO org, public;

-- 员工主表: 员工主表
CREATE TABLE IF NOT EXISTS org.employee (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    employee_no varchar(64) NOT NULL,
    person_name varchar(128) NOT NULL,
    id_no_cipher bytea,
    id_no_hash varchar(128),
    mobile_cipher bytea,
    employment_status varchar(32) NOT NULL,
    hire_date date,
    leave_date date,
    primary_org_id uuid,
    primary_position_id uuid
);
COMMENT ON TABLE org.employee IS '员工主表｜员工主表';
COMMENT ON COLUMN org.employee.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN org.employee.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.employee_no IS '员工编号｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.person_name IS '姓名｜敏感级别:P2-个人';
COMMENT ON COLUMN org.employee.id_no_cipher IS '证件号密文｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN org.employee.id_no_hash IS '证件号哈希｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.mobile_cipher IS '手机号密文｜敏感级别:P2-个人';
COMMENT ON COLUMN org.employee.employment_status IS '在职状态｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.hire_date IS '入职日期｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.leave_date IS '离职日期｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.primary_org_id IS '主组织ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee.primary_position_id IS '主岗位ID｜敏感级别:P1-内部';

-- 员工任职表: 员工任职表
CREATE TABLE IF NOT EXISTS org.employee_position (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    employee_id uuid NOT NULL,
    position_id uuid NOT NULL,
    org_id uuid NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    effective_start_date date NOT NULL,
    effective_end_date date,
    status varchar(32) DEFAULT 'ACTIVE' NOT NULL
);
COMMENT ON TABLE org.employee_position IS '员工任职表｜员工任职表';
COMMENT ON COLUMN org.employee_position.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN org.employee_position.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.employee_id IS '员工ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.position_id IS '岗位ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.org_id IS '组织ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.is_primary IS '主岗位｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.effective_start_date IS '开始日期｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.effective_end_date IS '结束日期｜敏感级别:P1-内部';
COMMENT ON COLUMN org.employee_position.status IS '状态｜敏感级别:P1-内部';

-- 组织机构表: 组织机构表
CREATE TABLE IF NOT EXISTS org.organization (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    org_code varchar(64) NOT NULL,
    org_name varchar(128) NOT NULL,
    org_type varchar(32) NOT NULL,
    parent_id uuid,
    path ltree,
    manager_employee_id uuid,
    status varchar(32) DEFAULT 'ACTIVE' NOT NULL
);
COMMENT ON TABLE org.organization IS '组织机构表｜组织机构表';
COMMENT ON COLUMN org.organization.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN org.organization.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.org_code IS '组织编码｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.org_name IS '组织名称｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.org_type IS '组织类型｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.parent_id IS '上级组织ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.path IS '组织路径｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.manager_employee_id IS '负责人ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.organization.status IS '状态｜敏感级别:P1-内部';

-- 岗位表: 岗位表
CREATE TABLE IF NOT EXISTS org.position (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    position_code varchar(64) NOT NULL,
    position_name varchar(128) NOT NULL,
    org_id uuid NOT NULL,
    grade_id uuid,
    status varchar(32) DEFAULT 'ACTIVE' NOT NULL
);
COMMENT ON TABLE org.position IS '岗位表｜岗位表';
COMMENT ON COLUMN org.position.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN org.position.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.position_code IS '岗位编码｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.position_name IS '岗位名称｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.org_id IS '所属组织｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.grade_id IS '职级ID｜敏感级别:P1-内部';
COMMENT ON COLUMN org.position.status IS '状态｜敏感级别:P1-内部';
RESET ROLE;
