-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/39_reception_tables.sql
-- source_sha256: 19f5ae15de33289e5a3f8098c936d3810e3a8e9207d03d496ef6466abfdf465b
SET ROLE sjg_owner;
-- Schema: reception / 接待运营
SET search_path TO reception, public;

-- 接待变更主表: 承载临时变更的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS reception.change_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    expected_effective_at timestamptz,
    followup_complaint_summary text,
    guest_contact varchar(200),
    guest_count bigint NOT NULL,
    guest_team_name varchar(200) NOT NULL,
    guide_host_id varchar(32),
    itinerary_version varchar(64) NOT NULL,
    known_impact text,
    reception_level varchar(64) NOT NULL,
    reception_team_no varchar(64) NOT NULL,
    route_script_version varchar(64)
);
COMMENT ON TABLE reception.change_request IS '接待变更主表｜承载临时变更的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN reception.change_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN reception.change_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN reception.change_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN reception.change_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN reception.change_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.followup_complaint_summary IS '回访/客诉摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.guest_contact IS '联系人及电话｜敏感级别:P2-个人';
COMMENT ON COLUMN reception.change_request.guest_count IS '人数｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.guest_team_name IS '客户/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.guide_host_id IS '导游/接待负责人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.itinerary_version IS '唯一行程版本｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.reception_level IS '接待等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.reception_team_no IS '接待/团队编号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request.route_script_version IS '路线/讲解词版本｜敏感级别:P1-内部';

-- 接待变更明细项: 按field_code承载：after_snapshot、before_snapshot、resource_child_orders
CREATE TABLE IF NOT EXISTS reception.change_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE reception.change_request_item IS '接待变更明细项｜按field_code承载：after_snapshot、before_snapshot、resource_child_orders';
COMMENT ON COLUMN reception.change_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN reception.change_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.change_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 接待客诉主表: 承载接待客诉的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS reception.complaint (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    converted_to_case boolean,
    guest_team_name varchar(200) NOT NULL,
    immediate_risk_control text,
    incident_area_id varchar(64) NOT NULL,
    incident_occurred_at timestamptz NOT NULL,
    incident_patrol_no varchar(64) NOT NULL,
    incident_risk_level varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    reception_team_no varchar(64) NOT NULL,
    scene_description text NOT NULL
);
COMMENT ON TABLE reception.complaint IS '接待客诉主表｜承载接待客诉的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN reception.complaint.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN reception.complaint.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN reception.complaint.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN reception.complaint.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN reception.complaint.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.converted_to_case IS '是否转统一案件｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.guest_team_name IS '客户/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.immediate_risk_control IS '先行止险措施｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.incident_area_id IS '发生区域｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.incident_occurred_at IS '发生时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.incident_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.reception_team_no IS '接待/团队编号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.complaint.scene_description IS '现场情况｜敏感级别:P1-内部';

-- 导游执行主表: 承载导游执行的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS reception.guide_execution (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    attendance_type varchar(64) NOT NULL,
    followup_complaint_summary text,
    guest_contact varchar(200),
    guest_count bigint NOT NULL,
    guest_team_name varchar(200) NOT NULL,
    guide_host_id varchar(32),
    itinerary_version varchar(64) NOT NULL,
    reception_level varchar(64) NOT NULL,
    reception_team_no varchar(64) NOT NULL,
    route_script_version varchar(64),
    start_at timestamptz NOT NULL
);
COMMENT ON TABLE reception.guide_execution IS '导游执行主表｜承载导游执行的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN reception.guide_execution.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN reception.guide_execution.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN reception.guide_execution.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN reception.guide_execution.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN reception.guide_execution.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.attendance_type IS '假勤类型｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.followup_complaint_summary IS '回访/客诉摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.guest_contact IS '联系人及电话｜敏感级别:P2-个人';
COMMENT ON COLUMN reception.guide_execution.guest_count IS '人数｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.guest_team_name IS '客户/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.guide_host_id IS '导游/接待负责人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.itinerary_version IS '唯一行程版本｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.reception_level IS '接待等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.reception_team_no IS '接待/团队编号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.route_script_version IS '路线/讲解词版本｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution.start_at IS '开始时间｜敏感级别:P1-内部';

-- 导游执行明细项: 按field_code承载：resource_child_orders
CREATE TABLE IF NOT EXISTS reception.guide_execution_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE reception.guide_execution_item IS '导游执行明细项｜按field_code承载：resource_child_orders';
COMMENT ON COLUMN reception.guide_execution_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN reception.guide_execution_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.guide_execution_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 接待订单主表: 承载标准接待的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS reception.reception_order (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    budget_item_id varchar(32),
    cost_center_id varchar(32) NOT NULL,
    followup_complaint_summary text,
    guest_contact varchar(200),
    guest_count bigint NOT NULL,
    guest_team_name varchar(200) NOT NULL,
    guide_host_id varchar(32),
    itinerary_version varchar(64) NOT NULL,
    reception_level varchar(64) NOT NULL,
    reception_team_no varchar(64) NOT NULL,
    route_script_version varchar(64)
);
COMMENT ON TABLE reception.reception_order IS '接待订单主表｜承载标准接待的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN reception.reception_order.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN reception.reception_order.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN reception.reception_order.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN reception.reception_order.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN reception.reception_order.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.followup_complaint_summary IS '回访/客诉摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.guest_contact IS '联系人及电话｜敏感级别:P2-个人';
COMMENT ON COLUMN reception.reception_order.guest_count IS '人数｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.guest_team_name IS '客户/团队名称｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.guide_host_id IS '导游/接待负责人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.itinerary_version IS '唯一行程版本｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.reception_level IS '接待等级｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.reception_team_no IS '接待/团队编号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order.route_script_version IS '路线/讲解词版本｜敏感级别:P1-内部';

-- 接待订单明细项: 按field_code承载：resource_child_orders
CREATE TABLE IF NOT EXISTS reception.reception_order_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE reception.reception_order_item IS '接待订单明细项｜按field_code承载：resource_child_orders';
COMMENT ON COLUMN reception.reception_order_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN reception.reception_order_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN reception.reception_order_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
