-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/03_archive_tables.sql
-- source_sha256: 49305ce32c1e13728f09ca9daff5e8e286ba74d93c2dbe1731db51e911dbe7fa
SET ROLE sjg_owner;
-- Schema: archive / 档案管理
SET search_path TO archive, public;

-- 归档包主表: 承载归档接收的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS archive.archive_package (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    archive_category varchar(64) NOT NULL,
    archive_item_count bigint,
    archive_no varchar(64),
    archive_title varchar(200) NOT NULL,
    carrier_type varchar(64) NOT NULL,
    confidentiality_level varchar(64) NOT NULL,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    spec_model varchar(200),
    storage_location varchar(500)
);
COMMENT ON TABLE archive.archive_package IS '归档包主表｜承载归档接收的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN archive.archive_package.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN archive.archive_package.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN archive.archive_package.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN archive.archive_package.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN archive.archive_package.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.archive_category IS '档案类别｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.archive_item_count IS '档案件数｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN archive.archive_package.archive_no IS '档案编号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.archive_title IS '档案题名｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.carrier_type IS '载体类型｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.confidentiality_level IS '密级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package.storage_location IS '存储位置｜敏感级别:P1-内部';

-- 归档包明细项: 按field_code承载：transfer_manifest
CREATE TABLE IF NOT EXISTS archive.archive_package_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE archive.archive_package_item IS '归档包明细项｜按field_code承载：transfer_manifest';
COMMENT ON COLUMN archive.archive_package_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN archive.archive_package_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.archive_package_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 档案借阅主表: 承载借阅归还的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS archive.borrow_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    archive_category varchar(64) NOT NULL,
    archive_item_count bigint,
    archive_no varchar(64),
    archive_title varchar(200) NOT NULL,
    carrier_type varchar(64) NOT NULL,
    confidentiality_level varchar(64) NOT NULL,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    spec_model varchar(200),
    storage_location varchar(500)
);
COMMENT ON TABLE archive.borrow_request IS '档案借阅主表｜承载借阅归还的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN archive.borrow_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN archive.borrow_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN archive.borrow_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN archive.borrow_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN archive.borrow_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.archive_category IS '档案类别｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.archive_item_count IS '档案件数｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN archive.borrow_request.archive_no IS '档案编号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.archive_title IS '档案题名｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.carrier_type IS '载体类型｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.confidentiality_level IS '密级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request.storage_location IS '存储位置｜敏感级别:P1-内部';

-- 档案借阅明细项: 按field_code承载：transfer_manifest
CREATE TABLE IF NOT EXISTS archive.borrow_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE archive.borrow_request_item IS '档案借阅明细项｜按field_code承载：transfer_manifest';
COMMENT ON COLUMN archive.borrow_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN archive.borrow_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.borrow_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 档案销毁鉴定主表: 承载销毁鉴定的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS archive.disposal_appraisal (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    archive_category varchar(64) NOT NULL,
    archive_item_count bigint,
    archive_no varchar(64),
    archive_title varchar(200) NOT NULL,
    carrier_type varchar(64) NOT NULL,
    confidentiality_level varchar(64) NOT NULL,
    storage_location varchar(500)
);
COMMENT ON TABLE archive.disposal_appraisal IS '档案销毁鉴定主表｜承载销毁鉴定的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN archive.disposal_appraisal.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN archive.disposal_appraisal.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN archive.disposal_appraisal.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN archive.disposal_appraisal.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN archive.disposal_appraisal.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.archive_category IS '档案类别｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.archive_item_count IS '档案件数｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN archive.disposal_appraisal.archive_no IS '档案编号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.archive_title IS '档案题名｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.carrier_type IS '载体类型｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.confidentiality_level IS '密级｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal.storage_location IS '存储位置｜敏感级别:P1-内部';

-- 档案销毁鉴定明细项: 按field_code承载：transfer_manifest
CREATE TABLE IF NOT EXISTS archive.disposal_appraisal_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE archive.disposal_appraisal_item IS '档案销毁鉴定明细项｜按field_code承载：transfer_manifest';
COMMENT ON COLUMN archive.disposal_appraisal_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN archive.disposal_appraisal_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN archive.disposal_appraisal_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
