-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/41_sales_tables.sql
-- source_sha256: 958ba526ad407f171fcb9e93c34a00b165bce7166503dfe7aaee21d5356565d8
SET ROLE sjg_owner;
-- Schema: sales / 销售运营
SET search_path TO sales, public;

-- 客户移交主表: 承载客户移交的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS sales.customer_handover (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    contact_name varchar(100),
    contact_phone varchar(32),
    customer_id varchar(32) NOT NULL,
    customer_name varchar(200) NOT NULL,
    expected_close_date date,
    expected_revenue numeric(18,2),
    lead_opportunity_no varchar(64),
    lead_source varchar(64),
    person_name varchar(50) NOT NULL,
    person_no varchar(32) NOT NULL,
    sales_owner_id varchar(32) NOT NULL
);
COMMENT ON TABLE sales.customer_handover IS '客户移交主表｜承载客户移交的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN sales.customer_handover.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.customer_handover.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN sales.customer_handover.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN sales.customer_handover.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN sales.customer_handover.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.contact_name IS '联系人｜敏感级别:P2-个人';
COMMENT ON COLUMN sales.customer_handover.contact_phone IS '联系电话｜敏感级别:P2-个人｜规则:手机号格式';
COMMENT ON COLUMN sales.customer_handover.customer_id IS '客户编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.customer_name IS '客户名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.expected_close_date IS '预计成交日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.expected_revenue IS '预计成交金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.lead_opportunity_no IS '线索/商机编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.lead_source IS '线索来源｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.person_name IS '姓名｜敏感级别:P2-个人';
COMMENT ON COLUMN sales.customer_handover.person_no IS '人员/候选人编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover.sales_owner_id IS '负责人/归属｜敏感级别:P1-内部';

-- 客户移交明细项: 按field_code承载：contract_order_no
CREATE TABLE IF NOT EXISTS sales.customer_handover_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE sales.customer_handover_item IS '客户移交明细项｜按field_code承载：contract_order_no';
COMMENT ON COLUMN sales.customer_handover_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.customer_handover_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.customer_handover_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 销售成交主表: 承载销售成交的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS sales.deal (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    contact_name varchar(100),
    contact_phone varchar(32),
    customer_id varchar(32) NOT NULL,
    customer_name varchar(200) NOT NULL,
    document_type varchar(64) NOT NULL,
    expected_close_date date,
    expected_revenue numeric(18,2),
    lead_opportunity_no varchar(64),
    lead_source varchar(64),
    sales_owner_id varchar(32) NOT NULL
);
COMMENT ON TABLE sales.deal IS '销售成交主表｜承载销售成交的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN sales.deal.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.deal.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN sales.deal.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN sales.deal.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN sales.deal.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.contact_name IS '联系人｜敏感级别:P2-个人';
COMMENT ON COLUMN sales.deal.contact_phone IS '联系电话｜敏感级别:P2-个人｜规则:手机号格式';
COMMENT ON COLUMN sales.deal.customer_id IS '客户编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.customer_name IS '客户名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.document_type IS '文档类型｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.expected_close_date IS '预计成交日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.expected_revenue IS '预计成交金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.lead_opportunity_no IS '线索/商机编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.lead_source IS '线索来源｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal.sales_owner_id IS '负责人/归属｜敏感级别:P1-内部';

-- 销售成交明细项: 按field_code承载：contract_order_no
CREATE TABLE IF NOT EXISTS sales.deal_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE sales.deal_item IS '销售成交明细项｜按field_code承载：contract_order_no';
COMMENT ON COLUMN sales.deal_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.deal_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.deal_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 销售线索主表: 承载线索转商机的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS sales.lead (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    contact_name varchar(100),
    contact_phone varchar(32),
    customer_id varchar(32) NOT NULL,
    customer_name varchar(200) NOT NULL,
    expected_close_date date,
    expected_revenue numeric(18,2),
    lead_opportunity_no varchar(64),
    lead_source varchar(64),
    period_or_course_no varchar(32) NOT NULL,
    sales_owner_id varchar(32) NOT NULL
);
COMMENT ON TABLE sales.lead IS '销售线索主表｜承载线索转商机的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN sales.lead.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.lead.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN sales.lead.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN sales.lead.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN sales.lead.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.contact_name IS '联系人｜敏感级别:P2-个人';
COMMENT ON COLUMN sales.lead.contact_phone IS '联系电话｜敏感级别:P2-个人｜规则:手机号格式';
COMMENT ON COLUMN sales.lead.customer_id IS '客户编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.customer_name IS '客户名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.expected_close_date IS '预计成交日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.expected_revenue IS '预计成交金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.lead_opportunity_no IS '线索/商机编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.lead_source IS '线索来源｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.period_or_course_no IS '周期/课程编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead.sales_owner_id IS '负责人/归属｜敏感级别:P1-内部';

-- 销售线索明细项: 按field_code承载：contract_order_no
CREATE TABLE IF NOT EXISTS sales.lead_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE sales.lead_item IS '销售线索明细项｜按field_code承载：contract_order_no';
COMMENT ON COLUMN sales.lead_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.lead_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.lead_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 二次销售主表: 承载二次销售的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS sales.secondary_sale (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    contact_name varchar(100),
    contact_phone varchar(32),
    customer_id varchar(32) NOT NULL,
    customer_name varchar(200) NOT NULL,
    expected_close_date date,
    expected_revenue numeric(18,2),
    lead_opportunity_no varchar(64),
    lead_source varchar(64),
    order_no varchar(64) NOT NULL,
    sales_channel varchar(64) NOT NULL,
    sales_owner_id varchar(32) NOT NULL
);
COMMENT ON TABLE sales.secondary_sale IS '二次销售主表｜承载二次销售的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN sales.secondary_sale.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.secondary_sale.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN sales.secondary_sale.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN sales.secondary_sale.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN sales.secondary_sale.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.contact_name IS '联系人｜敏感级别:P2-个人';
COMMENT ON COLUMN sales.secondary_sale.contact_phone IS '联系电话｜敏感级别:P2-个人｜规则:手机号格式';
COMMENT ON COLUMN sales.secondary_sale.customer_id IS '客户编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.customer_name IS '客户名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.expected_close_date IS '预计成交日期｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.expected_revenue IS '预计成交金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.lead_opportunity_no IS '线索/商机编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.lead_source IS '线索来源｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.order_no IS '订单编号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.sales_channel IS '销售渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale.sales_owner_id IS '负责人/归属｜敏感级别:P1-内部';

-- 二次销售明细项: 按field_code承载：contract_order_no
CREATE TABLE IF NOT EXISTS sales.secondary_sale_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE sales.secondary_sale_item IS '二次销售明细项｜按field_code承载：contract_order_no';
COMMENT ON COLUMN sales.secondary_sale_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN sales.secondary_sale_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN sales.secondary_sale_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
