-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/42_security_tables.sql
-- source_sha256: f335c853541aa5efcf49c3844acba7eee1150beeb706c5c34750c386ca665659
SET ROLE sjg_owner;
-- Schema: security / 安保管理
SET search_path TO security, public;

-- 客流预警主表: 承载客流预警的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS security.crowd_alert (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    converted_to_case boolean,
    immediate_risk_control text,
    incident_area_id varchar(64) NOT NULL,
    incident_occurred_at timestamptz NOT NULL,
    incident_patrol_no varchar(64) NOT NULL,
    incident_risk_level varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    scene_description text NOT NULL
);
COMMENT ON TABLE security.crowd_alert IS '客流预警主表｜承载客流预警的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN security.crowd_alert.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN security.crowd_alert.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN security.crowd_alert.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN security.crowd_alert.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN security.crowd_alert.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.converted_to_case IS '是否转统一案件｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.immediate_risk_control IS '先行止险措施｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.incident_area_id IS '发生区域｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.incident_occurred_at IS '发生时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.incident_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN security.crowd_alert.scene_description IS '现场情况｜敏感级别:P1-内部';

-- 活动安保方案主表: 承载活动安保的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS security.event_security_plan (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    converted_to_case boolean,
    immediate_risk_control text,
    incident_area_id varchar(64) NOT NULL,
    incident_occurred_at timestamptz NOT NULL,
    incident_patrol_no varchar(64) NOT NULL,
    incident_risk_level varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    scene_description text NOT NULL
);
COMMENT ON TABLE security.event_security_plan IS '活动安保方案主表｜承载活动安保的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN security.event_security_plan.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN security.event_security_plan.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN security.event_security_plan.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN security.event_security_plan.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN security.event_security_plan.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.converted_to_case IS '是否转统一案件｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.immediate_risk_control IS '先行止险措施｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.incident_area_id IS '发生区域｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.incident_occurred_at IS '发生时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.incident_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN security.event_security_plan.scene_description IS '现场情况｜敏感级别:P1-内部';

-- 巡逻任务主表: 承载日常巡逻的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS security.patrol_task (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    attendance_type varchar(64) NOT NULL,
    converted_to_case boolean,
    immediate_risk_control text,
    incident_area_id varchar(64) NOT NULL,
    incident_occurred_at timestamptz NOT NULL,
    incident_patrol_no varchar(64) NOT NULL,
    incident_risk_level varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    scene_description text NOT NULL,
    start_at timestamptz NOT NULL
);
COMMENT ON TABLE security.patrol_task IS '巡逻任务主表｜承载日常巡逻的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN security.patrol_task.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN security.patrol_task.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN security.patrol_task.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN security.patrol_task.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN security.patrol_task.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.attendance_type IS '假勤类型｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.converted_to_case IS '是否转统一案件｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.immediate_risk_control IS '先行止险措施｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.incident_area_id IS '发生区域｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.incident_occurred_at IS '发生时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.incident_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.scene_description IS '现场情况｜敏感级别:P1-内部';
COMMENT ON COLUMN security.patrol_task.start_at IS '开始时间｜敏感级别:P1-内部';

-- 安全事件主表: 承载安全事件的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS security.security_incident (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    converted_to_case boolean,
    immediate_risk_control text,
    incident_area_id varchar(64) NOT NULL,
    incident_occurred_at timestamptz NOT NULL,
    incident_patrol_no varchar(64) NOT NULL,
    incident_risk_level varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    scene_description text NOT NULL
);
COMMENT ON TABLE security.security_incident IS '安全事件主表｜承载安全事件的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN security.security_incident.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN security.security_incident.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN security.security_incident.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN security.security_incident.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN security.security_incident.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.converted_to_case IS '是否转统一案件｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.immediate_risk_control IS '先行止险措施｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.incident_area_id IS '发生区域｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.incident_occurred_at IS '发生时间｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.incident_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN security.security_incident.scene_description IS '现场情况｜敏感级别:P1-内部';
RESET ROLE;
