-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/43_ticketing_tables.sql
-- source_sha256: da29be61ebea4240069f43400c363eb9f6192a951a693139707a531e67978e1d
SET ROLE sjg_owner;
-- Schema: ticketing / 票务服务
SET search_path TO ticketing, public;

-- 离线检票事件主表: 承载离线检票的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS ticketing.offline_check_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    environment varchar(64) NOT NULL,
    order_amount numeric(18,2),
    order_no varchar(64) NOT NULL,
    pay_status varchar(64),
    product_id varchar(64) NOT NULL,
    quantity bigint NOT NULL,
    refund_change_reason text,
    sales_channel varchar(64) NOT NULL,
    service_date date NOT NULL,
    system_service_name varchar(200) NOT NULL,
    verification_status varchar(64)
);
COMMENT ON TABLE ticketing.offline_check_event IS '离线检票事件主表｜承载离线检票的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN ticketing.offline_check_event.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN ticketing.offline_check_event.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN ticketing.offline_check_event.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN ticketing.offline_check_event.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN ticketing.offline_check_event.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.order_amount IS '订单金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.order_no IS '订单编号｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.pay_status IS '支付状态｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.product_id IS '产品/票种｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.quantity IS '人数/数量｜敏感级别:P1-内部｜规则:大于0';
COMMENT ON COLUMN ticketing.offline_check_event.refund_change_reason IS '退款/改签原因｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.sales_channel IS '销售渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.service_date IS '游玩/履约日期｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event.verification_status IS '核销状态｜敏感级别:P1-内部';

-- 离线检票事件明细项: 按field_code承载：ticket_codes
CREATE TABLE IF NOT EXISTS ticketing.offline_check_event_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE ticketing.offline_check_event_item IS '离线检票事件明细项｜按field_code承载：ticket_codes';
COMMENT ON COLUMN ticketing.offline_check_event_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN ticketing.offline_check_event_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.offline_check_event_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 票务订单主表: 承载售检票闭环的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS ticketing.ticket_order (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    budget_item_id varchar(32),
    cost_center_id varchar(32) NOT NULL,
    order_amount numeric(18,2),
    order_no varchar(64) NOT NULL,
    pay_status varchar(64),
    product_id varchar(64) NOT NULL,
    quantity bigint NOT NULL,
    refund_change_reason text,
    sales_channel varchar(64) NOT NULL,
    service_date date NOT NULL,
    verification_status varchar(64)
);
COMMENT ON TABLE ticketing.ticket_order IS '票务订单主表｜承载售检票闭环的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN ticketing.ticket_order.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN ticketing.ticket_order.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN ticketing.ticket_order.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN ticketing.ticket_order.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN ticketing.ticket_order.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.order_amount IS '订单金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.order_no IS '订单编号｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.pay_status IS '支付状态｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.product_id IS '产品/票种｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.quantity IS '人数/数量｜敏感级别:P1-内部｜规则:大于0';
COMMENT ON COLUMN ticketing.ticket_order.refund_change_reason IS '退款/改签原因｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.sales_channel IS '销售渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.service_date IS '游玩/履约日期｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order.verification_status IS '核销状态｜敏感级别:P1-内部';

-- 票务订单明细项: 按field_code承载：ticket_codes
CREATE TABLE IF NOT EXISTS ticketing.ticket_order_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE ticketing.ticket_order_item IS '票务订单明细项｜按field_code承载：ticket_codes';
COMMENT ON COLUMN ticketing.ticket_order_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN ticketing.ticket_order_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_order_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 退款改签主表: 承载退款改签的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS ticketing.ticket_refund_change (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    budget_item_id varchar(32),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    cost_center_id varchar(32) NOT NULL,
    expected_effective_at timestamptz,
    known_impact text,
    order_amount numeric(18,2),
    order_no varchar(64) NOT NULL,
    pay_status varchar(64),
    product_id varchar(64) NOT NULL,
    quantity bigint NOT NULL,
    refund_change_reason text,
    sales_channel varchar(64) NOT NULL,
    service_date date NOT NULL,
    verification_status varchar(64)
);
COMMENT ON TABLE ticketing.ticket_refund_change IS '退款改签主表｜承载退款改签的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN ticketing.ticket_refund_change.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN ticketing.ticket_refund_change.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN ticketing.ticket_refund_change.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN ticketing.ticket_refund_change.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN ticketing.ticket_refund_change.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.order_amount IS '订单金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.order_no IS '订单编号｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.pay_status IS '支付状态｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.product_id IS '产品/票种｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.quantity IS '人数/数量｜敏感级别:P1-内部｜规则:大于0';
COMMENT ON COLUMN ticketing.ticket_refund_change.refund_change_reason IS '退款/改签原因｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.sales_channel IS '销售渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.service_date IS '游玩/履约日期｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change.verification_status IS '核销状态｜敏感级别:P1-内部';

-- 退款改签明细项: 按field_code承载：after_snapshot、before_snapshot、ticket_codes
CREATE TABLE IF NOT EXISTS ticketing.ticket_refund_change_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE ticketing.ticket_refund_change_item IS '退款改签明细项｜按field_code承载：after_snapshot、before_snapshot、ticket_codes';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN ticketing.ticket_refund_change_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
