-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/04_asset_tables.sql
-- source_sha256: af8fd90dd6366eed64659d451115cffbf25fd352b5f5a016a98aa9564cef0672
SET ROLE sjg_owner;
-- Schema: asset / 资产仓储
SET search_path TO asset, public;

-- 资产报废处置主表: 承载报废处置的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS asset.asset_disposal (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    asset_condition varchar(64),
    batch_serial_no varchar(128),
    book_value numeric(18,2),
    custodian_id varchar(32),
    incident_patrol_no varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    spec_model varchar(200),
    stock_quantity numeric(18,6) NOT NULL,
    unit varchar(64) NOT NULL,
    warehouse_location_id varchar(64) NOT NULL
);
COMMENT ON TABLE asset.asset_disposal IS '资产报废处置主表｜承载报废处置的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN asset.asset_disposal.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN asset.asset_disposal.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN asset.asset_disposal.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN asset.asset_disposal.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN asset.asset_disposal.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.asset_condition IS '状态/成色｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.batch_serial_no IS '批次/序列号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.book_value IS '账面价值｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN asset.asset_disposal.custodian_id IS '责任人/领用人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.stock_quantity IS '数量｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN asset.asset_disposal.unit IS '单位｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_disposal.warehouse_location_id IS '仓库/存放位置｜敏感级别:P1-内部';

-- 资产领借调还主表: 承载领借调还的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS asset.asset_use_transaction (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    asset_condition varchar(64),
    batch_serial_no varchar(128),
    book_value numeric(18,2),
    custodian_id varchar(32),
    employee_event_type varchar(64) NOT NULL,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    spec_model varchar(200),
    stock_quantity numeric(18,6) NOT NULL,
    unit varchar(64) NOT NULL,
    warehouse_location_id varchar(64) NOT NULL
);
COMMENT ON TABLE asset.asset_use_transaction IS '资产领借调还主表｜承载领借调还的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN asset.asset_use_transaction.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN asset.asset_use_transaction.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN asset.asset_use_transaction.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN asset.asset_use_transaction.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN asset.asset_use_transaction.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.asset_condition IS '状态/成色｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.batch_serial_no IS '批次/序列号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.book_value IS '账面价值｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN asset.asset_use_transaction.custodian_id IS '责任人/领用人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.employee_event_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.stock_quantity IS '数量｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN asset.asset_use_transaction.unit IS '单位｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.asset_use_transaction.warehouse_location_id IS '仓库/存放位置｜敏感级别:P1-内部';

-- 资产入库主表: 承载入库的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS asset.stock_in (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    asset_condition varchar(64),
    batch_serial_no varchar(128),
    book_value numeric(18,2),
    custodian_id varchar(32),
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    purchase_category varchar(64) NOT NULL,
    purchase_request_no varchar(32),
    spec_model varchar(200),
    stock_quantity numeric(18,6) NOT NULL,
    unit varchar(64) NOT NULL,
    warehouse_location_id varchar(64) NOT NULL
);
COMMENT ON TABLE asset.stock_in IS '资产入库主表｜承载入库的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN asset.stock_in.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN asset.stock_in.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN asset.stock_in.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN asset.stock_in.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN asset.stock_in.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.asset_condition IS '状态/成色｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.batch_serial_no IS '批次/序列号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.book_value IS '账面价值｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN asset.stock_in.custodian_id IS '责任人/领用人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.purchase_category IS '采购品类｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.purchase_request_no IS '采购需求编号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.stock_quantity IS '数量｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN asset.stock_in.unit IS '单位｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stock_in.warehouse_location_id IS '仓库/存放位置｜敏感级别:P1-内部';

-- 资产盘点主表: 承载盘点的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS asset.stocktake (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    asset_condition varchar(64),
    batch_serial_no varchar(128),
    book_value numeric(18,2),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    custodian_id varchar(32),
    expected_effective_at timestamptz,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    known_impact text,
    spec_model varchar(200),
    stock_quantity numeric(18,6) NOT NULL,
    unit varchar(64) NOT NULL,
    warehouse_location_id varchar(64) NOT NULL
);
COMMENT ON TABLE asset.stocktake IS '资产盘点主表｜承载盘点的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN asset.stocktake.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN asset.stocktake.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN asset.stocktake.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN asset.stocktake.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN asset.stocktake.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.asset_condition IS '状态/成色｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.batch_serial_no IS '批次/序列号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.book_value IS '账面价值｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN asset.stocktake.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.custodian_id IS '责任人/领用人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.spec_model IS '规格型号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.stock_quantity IS '数量｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN asset.stocktake.unit IS '单位｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake.warehouse_location_id IS '仓库/存放位置｜敏感级别:P1-内部';

-- 资产盘点明细项: 按field_code承载：after_snapshot、before_snapshot
CREATE TABLE IF NOT EXISTS asset.stocktake_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE asset.stocktake_item IS '资产盘点明细项｜按field_code承载：after_snapshot、before_snapshot';
COMMENT ON COLUMN asset.stocktake_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN asset.stocktake_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN asset.stocktake_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
