-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/06_audit_tables.sql
-- source_sha256: 3d99bba344b3377558412a64204ddd78e3c44ca0f559edfe44c8ec7dd39053ea
SET ROLE sjg_owner;
-- Schema: audit / 审计治理
SET search_path TO audit, public;

-- 审计策略表: 审计策略表
CREATE TABLE IF NOT EXISTS audit.audit_policy (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    policy_code varchar(64) NOT NULL,
    business_type varchar(128),
    retention_days integer NOT NULL,
    evidence_chain_policy jsonb,
    masking_policy jsonb,
    encryption_policy jsonb
);
COMMENT ON TABLE audit.audit_policy IS '审计策略表｜审计策略表';
COMMENT ON COLUMN audit.audit_policy.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN audit.audit_policy.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.policy_code IS '策略编码｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.business_type IS '业务类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.retention_days IS '保留天数｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.evidence_chain_policy IS '证据链策略｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.masking_policy IS '脱敏策略｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.audit_policy.encryption_policy IS '加密策略｜敏感级别:P1-内部';

-- 敏感导出申请主表: 敏感导出申请主表
CREATE TABLE IF NOT EXISTS audit.data_export_request (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    export_type varchar(64) NOT NULL,
    data_scope jsonb NOT NULL,
    field_scope jsonb NOT NULL,
    purpose text NOT NULL,
    approval_level varchar(32) NOT NULL,
    watermark_text varchar(255),
    expire_at timestamptz,
    file_id uuid,
    download_count integer DEFAULT 0 NOT NULL,
    actual_amount numeric(18,2),
    actual_end_at timestamptz,
    actual_start_at timestamptz NOT NULL,
    business_date date NOT NULL,
    environment varchar(64) NOT NULL,
    implementation_window tstzrange,
    result_summary text NOT NULL,
    rollback_plan text,
    system_service_name varchar(200) NOT NULL,
    tech_impact_scope text NOT NULL,
    tech_risk_level varchar(64) NOT NULL,
    tech_work_item_no varchar(64),
    verification_test_result text,
    version_build_no varchar(100)
);
COMMENT ON TABLE audit.data_export_request IS '敏感导出申请主表｜敏感导出申请主表';
COMMENT ON COLUMN audit.data_export_request.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN audit.data_export_request.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN audit.data_export_request.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN audit.data_export_request.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN audit.data_export_request.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.export_type IS '导出类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.data_scope IS '数据范围｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.field_scope IS '字段范围｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.purpose IS '用途｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.approval_level IS '审批等级｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.watermark_text IS '水印｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.expire_at IS '下载过期时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.file_id IS '导出文件ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.download_count IS '下载次数｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.actual_end_at IS '实际结束时间｜敏感级别:P1-内部｜规则:不得早于开始时间';
COMMENT ON COLUMN audit.data_export_request.actual_start_at IS '实际开始时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.business_date IS '业务发生日期｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.implementation_window IS '实施窗口｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.rollback_plan IS '回退方案｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.tech_impact_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.tech_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.tech_work_item_no IS '变更/需求/缺陷编号｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.verification_test_result IS '健康检查/测试结果｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request.version_build_no IS '版本/构建号｜敏感级别:P1-内部';

-- 敏感导出申请明细项: 按field_code承载：tech_logs_reports
CREATE TABLE IF NOT EXISTS audit.data_export_request_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE audit.data_export_request_item IS '敏感导出申请明细项｜按field_code承载：tech_logs_reports';
COMMENT ON COLUMN audit.data_export_request_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN audit.data_export_request_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_export_request_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 数据质量问题主表: 数据质量问题主表
CREATE TABLE IF NOT EXISTS audit.data_quality_issue (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    rule_code varchar(64) NOT NULL,
    object_type varchar(128) NOT NULL,
    object_id uuid,
    issue_type varchar(64) NOT NULL,
    severity varchar(16) NOT NULL,
    before_snapshot jsonb,
    after_snapshot jsonb,
    root_cause text,
    resolution_action text,
    verified_at timestamptz,
    actual_amount numeric(18,2),
    actual_end_at timestamptz,
    actual_start_at timestamptz NOT NULL,
    business_date date NOT NULL,
    employee_event_type varchar(64) NOT NULL,
    environment varchar(64) NOT NULL,
    implementation_window tstzrange,
    result_summary text NOT NULL,
    rollback_plan text,
    system_service_name varchar(200) NOT NULL,
    tech_impact_scope text NOT NULL,
    tech_risk_level varchar(64) NOT NULL,
    tech_work_item_no varchar(64),
    verification_test_result text,
    version_build_no varchar(100)
);
COMMENT ON TABLE audit.data_quality_issue IS '数据质量问题主表｜数据质量问题主表';
COMMENT ON COLUMN audit.data_quality_issue.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN audit.data_quality_issue.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN audit.data_quality_issue.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN audit.data_quality_issue.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN audit.data_quality_issue.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.rule_code IS '质量规则编码｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.object_type IS '对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.object_id IS '对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.issue_type IS '问题类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.severity IS '严重级别｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.before_snapshot IS '修复前快照｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.after_snapshot IS '修复后快照｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.root_cause IS '根因｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.resolution_action IS '解决动作｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.verified_at IS '验证时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.actual_end_at IS '实际结束时间｜敏感级别:P1-内部｜规则:不得早于开始时间';
COMMENT ON COLUMN audit.data_quality_issue.actual_start_at IS '实际开始时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.business_date IS '业务发生日期｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.employee_event_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.environment IS '环境｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.implementation_window IS '实施窗口｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.rollback_plan IS '回退方案｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.system_service_name IS '系统/服务名称｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.tech_impact_scope IS '影响范围｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.tech_risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.tech_work_item_no IS '变更/需求/缺陷编号｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.verification_test_result IS '健康检查/测试结果｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue.version_build_no IS '版本/构建号｜敏感级别:P1-内部';

-- 数据质量问题明细项: 按field_code承载：tech_logs_reports
CREATE TABLE IF NOT EXISTS audit.data_quality_issue_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE audit.data_quality_issue_item IS '数据质量问题明细项｜按field_code承载：tech_logs_reports';
COMMENT ON COLUMN audit.data_quality_issue_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN audit.data_quality_issue_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_quality_issue_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
