-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/08_catering_tables.sql
-- source_sha256: 9747a22fbc4371ed98562c501fe0dac41b909520429cb334493662a6c4fff9c6
SET ROLE sjg_owner;
-- Schema: catering / 餐饮管理
SET search_path TO catering, public;

-- 食品安全事件主表: 承载食品安全事件的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS catering.food_safety_incident (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    allergy_taboo text,
    incident_patrol_no varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    meal_count bigint,
    meal_event_date date NOT NULL,
    meal_standard numeric(18,2),
    meal_transaction_no varchar(64),
    meal_type varchar(64) NOT NULL,
    sample_no varchar(64)
);
COMMENT ON TABLE catering.food_safety_incident IS '食品安全事件主表｜承载食品安全事件的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN catering.food_safety_incident.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.food_safety_incident.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN catering.food_safety_incident.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN catering.food_safety_incident.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN catering.food_safety_incident.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.allergy_taboo IS '过敏/禁忌信息｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN catering.food_safety_incident.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.meal_count IS '人数/份数｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.meal_event_date IS '用餐/事件日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.meal_standard IS '餐标｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.meal_transaction_no IS '结算/交易编号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.meal_type IS '餐次/餐饮类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident.sample_no IS '留样编号｜敏感级别:P1-内部';

-- 食品安全事件明细项: 按field_code承载：food_inspection、ingredient_batches、menu_items
CREATE TABLE IF NOT EXISTS catering.food_safety_incident_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE catering.food_safety_incident_item IS '食品安全事件明细项｜按field_code承载：food_inspection、ingredient_batches、menu_items';
COMMENT ON COLUMN catering.food_safety_incident_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.food_safety_incident_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.food_safety_incident_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 团餐订单主表: 承载团餐交付的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS catering.group_meal_order (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    allergy_taboo text,
    budget_item_id varchar(32),
    cost_center_id varchar(32) NOT NULL,
    meal_count bigint,
    meal_event_date date NOT NULL,
    meal_standard numeric(18,2),
    meal_transaction_no varchar(64),
    meal_type varchar(64) NOT NULL,
    sample_no varchar(64)
);
COMMENT ON TABLE catering.group_meal_order IS '团餐订单主表｜承载团餐交付的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN catering.group_meal_order.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.group_meal_order.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN catering.group_meal_order.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN catering.group_meal_order.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN catering.group_meal_order.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.allergy_taboo IS '过敏/禁忌信息｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN catering.group_meal_order.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.meal_count IS '人数/份数｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.meal_event_date IS '用餐/事件日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.meal_standard IS '餐标｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.meal_transaction_no IS '结算/交易编号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.meal_type IS '餐次/餐饮类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order.sample_no IS '留样编号｜敏感级别:P1-内部';

-- 团餐订单明细项: 按field_code承载：food_inspection、ingredient_batches、menu_items
CREATE TABLE IF NOT EXISTS catering.group_meal_order_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE catering.group_meal_order_item IS '团餐订单明细项｜按field_code承载：food_inspection、ingredient_batches、menu_items';
COMMENT ON COLUMN catering.group_meal_order_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.group_meal_order_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.group_meal_order_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 食材验收主表: 承载食材验收的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS catering.ingredient_acceptance (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    allergy_taboo text,
    item_asset_id varchar(64) NOT NULL,
    item_asset_name varchar(200) NOT NULL,
    meal_count bigint,
    meal_event_date date NOT NULL,
    meal_standard numeric(18,2),
    meal_transaction_no varchar(64),
    meal_type varchar(64) NOT NULL,
    sample_no varchar(64)
);
COMMENT ON TABLE catering.ingredient_acceptance IS '食材验收主表｜承载食材验收的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN catering.ingredient_acceptance.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.ingredient_acceptance.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN catering.ingredient_acceptance.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN catering.ingredient_acceptance.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN catering.ingredient_acceptance.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.allergy_taboo IS '过敏/禁忌信息｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN catering.ingredient_acceptance.item_asset_id IS '物料/资产编号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.item_asset_name IS '物料/资产名称｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.meal_count IS '人数/份数｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.meal_event_date IS '用餐/事件日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.meal_standard IS '餐标｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.meal_transaction_no IS '结算/交易编号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.meal_type IS '餐次/餐饮类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance.sample_no IS '留样编号｜敏感级别:P1-内部';

-- 食材验收明细项: 按field_code承载：food_inspection、ingredient_batches、menu_items
CREATE TABLE IF NOT EXISTS catering.ingredient_acceptance_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE catering.ingredient_acceptance_item IS '食材验收明细项｜按field_code承载：food_inspection、ingredient_batches、menu_items';
COMMENT ON COLUMN catering.ingredient_acceptance_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.ingredient_acceptance_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.ingredient_acceptance_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 餐卡结算主表: 承载餐卡结算的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS catering.meal_card_settlement (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    allergy_taboo text,
    budget_item_id varchar(32),
    change_action varchar(64) NOT NULL,
    change_reason text NOT NULL,
    cost_center_id varchar(32) NOT NULL,
    expected_effective_at timestamptz,
    known_impact text,
    meal_count bigint,
    meal_event_date date NOT NULL,
    meal_standard numeric(18,2),
    meal_transaction_no varchar(64),
    meal_type varchar(64) NOT NULL,
    sample_no varchar(64)
);
COMMENT ON TABLE catering.meal_card_settlement IS '餐卡结算主表｜承载餐卡结算的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN catering.meal_card_settlement.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.meal_card_settlement.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN catering.meal_card_settlement.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN catering.meal_card_settlement.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN catering.meal_card_settlement.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.allergy_taboo IS '过敏/禁忌信息｜敏感级别:P3-高度敏感';
COMMENT ON COLUMN catering.meal_card_settlement.budget_item_id IS '预算项目｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.change_action IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.change_reason IS '变更原因｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.cost_center_id IS '成本中心｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.expected_effective_at IS '期望生效时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.known_impact IS '已知影响｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.meal_count IS '人数/份数｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.meal_event_date IS '用餐/事件日期｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.meal_standard IS '餐标｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.meal_transaction_no IS '结算/交易编号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.meal_type IS '餐次/餐饮类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement.sample_no IS '留样编号｜敏感级别:P1-内部';

-- 餐卡结算明细项: 按field_code承载：after_snapshot、before_snapshot、food_inspection、ingredient_batches、menu_items
CREATE TABLE IF NOT EXISTS catering.meal_card_settlement_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE catering.meal_card_settlement_item IS '餐卡结算明细项｜按field_code承载：after_snapshot、before_snapshot、food_inspection、ingredient_batches、menu_items';
COMMENT ON COLUMN catering.meal_card_settlement_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN catering.meal_card_settlement_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN catering.meal_card_settlement_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
