-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/01_sjg_oms/09_cleaning_tables.sql
-- source_sha256: cb933773a5597fbc9751f76d5deb215be5f256c7ff30bc3de63816c75852b5e1
SET ROLE sjg_owner;
-- Schema: cleaning / 环卫管理
SET search_path TO cleaning, public;

-- 清洁任务主表: 承载日常清洁的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS cleaning.cleaning_task (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    attendance_type varchar(64) NOT NULL,
    cleaning_area_id varchar(64) NOT NULL,
    cleaning_standard_version varchar(32) NOT NULL,
    cleaning_time timestamptz NOT NULL,
    cleaning_type varchar(64) NOT NULL,
    duration_hours numeric(18,6) NOT NULL,
    end_at timestamptz NOT NULL,
    inspection_result varchar(64),
    self_check_result varchar(64),
    start_at timestamptz NOT NULL
);
COMMENT ON TABLE cleaning.cleaning_task IS '清洁任务主表｜承载日常清洁的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN cleaning.cleaning_task.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN cleaning.cleaning_task.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN cleaning.cleaning_task.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN cleaning.cleaning_task.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN cleaning.cleaning_task.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.attendance_type IS '假勤类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.cleaning_area_id IS '作业区域｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.cleaning_standard_version IS '作业标准版本｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.cleaning_time IS '计划/实际作业时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.cleaning_type IS '作业类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.duration_hours IS '折算时长（小时）｜敏感级别:P1-内部｜规则:不得小于0';
COMMENT ON COLUMN cleaning.cleaning_task.end_at IS '结束时间｜敏感级别:P1-内部｜规则:不得早于开始时间';
COMMENT ON COLUMN cleaning.cleaning_task.inspection_result IS '巡检/验收结果｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.self_check_result IS '自检结果｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task.start_at IS '开始时间｜敏感级别:P1-内部';

-- 清洁任务明细项: 按field_code承载：consumables_used
CREATE TABLE IF NOT EXISTS cleaning.cleaning_task_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE cleaning.cleaning_task_item IS '清洁任务明细项｜按field_code承载：consumables_used';
COMMENT ON COLUMN cleaning.cleaning_task_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN cleaning.cleaning_task_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.cleaning_task_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 环卫活动保障主表: 承载活动保障的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS cleaning.event_support (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    campaign_goal text NOT NULL,
    campaign_name varchar(200) NOT NULL,
    campaign_no varchar(32) NOT NULL,
    cleaning_area_id varchar(64) NOT NULL,
    cleaning_standard_version varchar(32) NOT NULL,
    cleaning_time timestamptz NOT NULL,
    cleaning_type varchar(64) NOT NULL,
    inspection_result varchar(64),
    self_check_result varchar(64),
    target_audience_desc text
);
COMMENT ON TABLE cleaning.event_support IS '环卫活动保障主表｜承载活动保障的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN cleaning.event_support.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN cleaning.event_support.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN cleaning.event_support.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN cleaning.event_support.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN cleaning.event_support.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.campaign_goal IS '活动目标｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.campaign_name IS '活动名称｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.campaign_no IS '活动/项目编号｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.cleaning_area_id IS '作业区域｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.cleaning_standard_version IS '作业标准版本｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.cleaning_time IS '计划/实际作业时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.cleaning_type IS '作业类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.inspection_result IS '巡检/验收结果｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.self_check_result IS '自检结果｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support.target_audience_desc IS '目标人群｜敏感级别:P1-内部';

-- 环卫活动保障明细项: 按field_code承载：consumables_used
CREATE TABLE IF NOT EXISTS cleaning.event_support_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE cleaning.event_support_item IS '环卫活动保障明细项｜按field_code承载：consumables_used';
COMMENT ON COLUMN cleaning.event_support_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN cleaning.event_support_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.event_support_item.sort_no IS '排序｜敏感级别:P1-内部';

-- 污染应急事件主表: 承载污染应急的稳定业务事实；流程动作、动态字段和附件分别落公共子表
CREATE TABLE IF NOT EXISTS cleaning.pollution_incident (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    business_no varchar(64) NOT NULL,
    workflow_instance_id uuid,
    status varchar(32) DEFAULT 'DRAFT' NOT NULL,
    version_no integer DEFAULT 0 NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    source_channel varchar(32),
    business_date date,
    subject varchar(255),
    reason text,
    priority varchar(16) DEFAULT 'NORMAL' NOT NULL,
    risk_level varchar(16),
    owner_center_id uuid,
    owner_department_id uuid,
    owner_employee_id uuid,
    planned_start_at timestamptz,
    planned_finish_at timestamptz,
    actual_start_at timestamptz,
    actual_end_at timestamptz,
    result_summary text,
    closed_at timestamptz,
    actual_amount numeric(18,2),
    cleaning_area_id varchar(64) NOT NULL,
    cleaning_standard_version varchar(32) NOT NULL,
    cleaning_time timestamptz NOT NULL,
    cleaning_type varchar(64) NOT NULL,
    incident_area_id varchar(64) NOT NULL,
    incident_occurred_at timestamptz NOT NULL,
    incident_patrol_no varchar(64) NOT NULL,
    incident_type varchar(64) NOT NULL,
    inspection_result varchar(64),
    self_check_result varchar(64)
);
COMMENT ON TABLE cleaning.pollution_incident IS '污染应急事件主表｜承载污染应急的稳定业务事实；流程动作、动态字段和附件分别落公共子表';
COMMENT ON COLUMN cleaning.pollution_incident.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN cleaning.pollution_incident.business_no IS '业务单号｜敏感级别:P1-内部｜规则:租户内唯一；由core.sequence_rule生成';
COMMENT ON COLUMN cleaning.pollution_incident.workflow_instance_id IS '流程实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.status IS '业务状态｜敏感级别:P1-内部｜规则:仅由状态机合法迁移';
COMMENT ON COLUMN cleaning.pollution_incident.version_no IS '乐观锁版本｜敏感级别:P1-内部｜规则:更新时version_no+1，冲突则拒绝';
COMMENT ON COLUMN cleaning.pollution_incident.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.source_channel IS '来源渠道｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.business_date IS '业务日期｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.subject IS '主题｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.reason IS '原因｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.priority IS '优先级｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.risk_level IS '风险等级｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.owner_center_id IS '归属中心｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.owner_department_id IS '归属部门｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.owner_employee_id IS '责任人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.planned_start_at IS '计划开始｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.planned_finish_at IS '计划完成｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.actual_start_at IS '实际开始｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.actual_end_at IS '实际完成｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.result_summary IS '结果摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.closed_at IS '关闭时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.cleaning_area_id IS '作业区域｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.cleaning_standard_version IS '作业标准版本｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.cleaning_time IS '计划/实际作业时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.cleaning_type IS '作业类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.incident_area_id IS '发生区域｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.incident_occurred_at IS '发生时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.incident_patrol_no IS '事件/巡检编号｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.incident_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.inspection_result IS '巡检/验收结果｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident.self_check_result IS '自检结果｜敏感级别:P1-内部';

-- 污染应急事件明细项: 按field_code承载：consumables_used
CREATE TABLE IF NOT EXISTS cleaning.pollution_incident_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid,
    updated_at timestamptz DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamptz,
    master_id uuid NOT NULL,
    field_code varchar(128) NOT NULL,
    item_seq integer DEFAULT 0 NOT NULL,
    item_key varchar(128),
    item_name varchar(255),
    item_value_text text,
    item_value_number numeric(24,8),
    item_value_json jsonb,
    related_object_type varchar(128),
    related_object_id uuid,
    amount numeric(18,2),
    quantity numeric(18,6),
    sort_no integer DEFAULT 0 NOT NULL
);
COMMENT ON TABLE cleaning.pollution_incident_item IS '污染应急事件明细项｜按field_code承载：consumables_used';
COMMENT ON COLUMN cleaning.pollution_incident_item.id IS '主键ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.tenant_id IS '租户ID｜敏感级别:P1-内部｜规则:所有业务唯一键必须包含tenant_id';
COMMENT ON COLUMN cleaning.pollution_incident_item.created_by IS '创建人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.created_at IS '创建时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.updated_by IS '更新人｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.updated_at IS '更新时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.is_deleted IS '逻辑删除｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.deleted_at IS '删除时间｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.master_id IS '主表ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.field_code IS '来源字段编码｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.item_seq IS '明细序号｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.item_key IS '明细键｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.item_name IS '明细名称｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.item_value_text IS '文本值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.item_value_number IS '数值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.item_value_json IS '结构化值｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.related_object_type IS '关联对象类型｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.related_object_id IS '关联对象ID｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.quantity IS '数量｜敏感级别:P1-内部';
COMMENT ON COLUMN cleaning.pollution_incident_item.sort_no IS '排序｜敏感级别:P1-内部';
RESET ROLE;
