-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/03_sjg_dw/02_analytics_tables.sql
-- source_sha256: 5642f69312c44c982ef09129fe08b4ceccb4a98fad65f96e985dc1eefb3c1ebd
SET ROLE sjg_owner;
-- Schema: analytics / 分析模型
SET search_path TO analytics, public;

-- 日期维度: 日期维度
CREATE TABLE IF NOT EXISTS analytics.dim_date (
    date_key integer NOT NULL PRIMARY KEY,
    full_date date NOT NULL,
    year smallint NOT NULL,
    month smallint NOT NULL,
    day smallint NOT NULL,
    week_of_year smallint NOT NULL,
    is_workday boolean NOT NULL
);
COMMENT ON TABLE analytics.dim_date IS '日期维度｜日期维度';
COMMENT ON COLUMN analytics.dim_date.date_key IS '日期键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_date.full_date IS '完整日期｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_date.year IS '年｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_date.month IS '月｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_date.day IS '日｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_date.week_of_year IS '周｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_date.is_workday IS '是否工作日｜敏感级别:P1-内部';

-- 员工维度: 员工维度
CREATE TABLE IF NOT EXISTS analytics.dim_employee (
    employee_key bigserial NOT NULL PRIMARY KEY,
    employee_id uuid NOT NULL,
    employee_no varchar(64) NOT NULL,
    employee_name_masked varchar(128),
    org_id uuid,
    position_id uuid,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    is_current boolean NOT NULL
);
COMMENT ON TABLE analytics.dim_employee IS '员工维度｜员工维度';
COMMENT ON COLUMN analytics.dim_employee.employee_key IS '代理键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.employee_id IS '源员工ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.employee_no IS '员工编号｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.employee_name_masked IS '脱敏姓名｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.org_id IS '组织ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.position_id IS '岗位ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.valid_from IS '有效开始｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.valid_to IS '有效结束｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_employee.is_current IS '当前版本｜敏感级别:P1-内部';

-- 组织维度: 组织维度
CREATE TABLE IF NOT EXISTS analytics.dim_org (
    org_key bigserial NOT NULL PRIMARY KEY,
    org_id uuid NOT NULL,
    org_code varchar(64) NOT NULL,
    org_name varchar(128) NOT NULL,
    org_path text,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    is_current boolean NOT NULL
);
COMMENT ON TABLE analytics.dim_org IS '组织维度｜组织维度';
COMMENT ON COLUMN analytics.dim_org.org_key IS '代理键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_org.org_id IS '源组织ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_org.org_code IS '组织编码｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_org.org_name IS '组织名称｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_org.org_path IS '组织路径｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_org.valid_from IS '有效开始｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_org.valid_to IS '有效结束｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_org.is_current IS '当前版本｜敏感级别:P1-内部';

-- 流程维度: 流程维度
CREATE TABLE IF NOT EXISTS analytics.dim_process (
    process_key integer NOT NULL PRIMARY KEY,
    process_code varchar(16) NOT NULL,
    process_name varchar(128) NOT NULL,
    module_name varchar(128) NOT NULL,
    owner_schema varchar(64) NOT NULL
);
COMMENT ON TABLE analytics.dim_process IS '流程维度｜流程维度';
COMMENT ON COLUMN analytics.dim_process.process_key IS '代理键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_process.process_code IS '流程编码｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_process.process_name IS '流程名称｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_process.module_name IS '模块名称｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.dim_process.owner_schema IS '归属Schema｜敏感级别:P1-内部';

-- 财务事实表: 财务事实表
CREATE TABLE IF NOT EXISTS analytics.fact_finance (
    tenant_id uuid NOT NULL,
    date_key integer NOT NULL,
    org_key bigint,
    business_type varchar(32) NOT NULL,
    business_id uuid NOT NULL,
    requested_amount numeric(18,2),
    approved_amount numeric(18,2),
    actual_amount numeric(18,2),
    currency varchar(3) DEFAULT 'CNY' NOT NULL,
    recorded_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE analytics.fact_finance IS '财务事实表｜财务事实表';
COMMENT ON COLUMN analytics.fact_finance.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.date_key IS '日期键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.org_key IS '组织键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.business_type IS '业务类型｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.business_id IS '业务ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.requested_amount IS '申请金额｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.approved_amount IS '批准金额｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.actual_amount IS '实际金额｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.currency IS '币种｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_finance.recorded_at IS '入仓时间｜敏感级别:P1-内部';

-- 服务交付事实表: 服务交付事实表
CREATE TABLE IF NOT EXISTS analytics.fact_service_delivery (
    tenant_id uuid NOT NULL,
    date_key integer NOT NULL,
    service_type varchar(64) NOT NULL,
    business_id uuid NOT NULL,
    customer_id uuid,
    guest_count integer,
    revenue_amount numeric(18,2),
    satisfaction_score numeric(6,2),
    complaint_count integer DEFAULT 0 NOT NULL,
    recorded_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE analytics.fact_service_delivery IS '服务交付事实表｜服务交付事实表';
COMMENT ON COLUMN analytics.fact_service_delivery.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.date_key IS '日期键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.service_type IS '服务类型｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.business_id IS '业务ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.customer_id IS '客户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.guest_count IS '人数｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.revenue_amount IS '收入金额｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.satisfaction_score IS '满意度｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.complaint_count IS '客诉数｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_service_delivery.recorded_at IS '入仓时间｜敏感级别:P1-内部';

-- 流程事实表: 流程事实表
CREATE TABLE IF NOT EXISTS analytics.fact_workflow (
    tenant_id uuid NOT NULL,
    date_key integer NOT NULL,
    process_key integer NOT NULL,
    initiator_employee_key bigint,
    owner_org_key bigint,
    instance_id uuid NOT NULL,
    status varchar(32) NOT NULL,
    duration_minutes numeric(18,2),
    sla_breached boolean NOT NULL,
    return_count integer DEFAULT 0 NOT NULL,
    amount numeric(18,2),
    recorded_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE analytics.fact_workflow IS '流程事实表｜流程事实表';
COMMENT ON COLUMN analytics.fact_workflow.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.date_key IS '日期键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.process_key IS '流程键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.initiator_employee_key IS '发起人员工键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.owner_org_key IS '归属组织键｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.instance_id IS '实例ID｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.status IS '状态｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.duration_minutes IS '耗时分钟｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.sla_breached IS '是否超时｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.return_count IS '退回次数｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.amount IS '金额｜敏感级别:P1-内部';
COMMENT ON COLUMN analytics.fact_workflow.recorded_at IS '入仓时间｜敏感级别:P1-内部';
RESET ROLE;
