-- PHASE-03 platform database role baseline.
-- Passwords/secrets are intentionally NOT stored in Git/Flyway.
-- Environment provisioning may set passwords on LOGIN roles after this migration.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_owner') THEN
    CREATE ROLE sjg_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_migration') THEN
    CREATE ROLE sjg_migration LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_api_runtime') THEN
    CREATE ROLE sjg_api_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_worker_runtime') THEN
    CREATE ROLE sjg_worker_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_audit_writer') THEN
    CREATE ROLE sjg_audit_writer LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_auditor') THEN
    CREATE ROLE sjg_auditor LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_dw_writer') THEN
    CREATE ROLE sjg_dw_writer LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_dw_reader') THEN
    CREATE ROLE sjg_dw_reader LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
  -- Compatibility role referenced by the approved audit DDL. New runtime code MUST NOT use it.
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_app') THEN
    CREATE ROLE sjg_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
END
$$;

ALTER ROLE sjg_owner NOSUPERUSER NOCREATEDB NOCREATEROLE NOLOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_migration NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_api_runtime NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_worker_runtime NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_audit_writer NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_auditor NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_dw_writer NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_dw_reader NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN NOINHERIT NOREPLICATION NOBYPASSRLS;

GRANT sjg_owner TO sjg_migration;
