#!/bin/sh
set -eu

: "${SJG_MIGRATION_DB_PASSWORD:?missing SJG_MIGRATION_DB_PASSWORD}"
: "${SJG_API_DB_PASSWORD:?missing SJG_API_DB_PASSWORD}"
: "${SJG_WORKER_DB_PASSWORD:?missing SJG_WORKER_DB_PASSWORD}"
: "${SJG_AUDIT_WRITER_DB_PASSWORD:?missing SJG_AUDIT_WRITER_DB_PASSWORD}"
: "${SJG_AUDITOR_DB_PASSWORD:?missing SJG_AUDITOR_DB_PASSWORD}"
: "${SJG_DW_WRITER_DB_PASSWORD:?missing SJG_DW_WRITER_DB_PASSWORD}"
: "${SJG_DW_READER_DB_PASSWORD:?missing SJG_DW_READER_DB_PASSWORD}"

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  -v migration_password="$SJG_MIGRATION_DB_PASSWORD" \
  -v api_password="$SJG_API_DB_PASSWORD" \
  -v worker_password="$SJG_WORKER_DB_PASSWORD" \
  -v audit_writer_password="$SJG_AUDIT_WRITER_DB_PASSWORD" \
  -v auditor_password="$SJG_AUDITOR_DB_PASSWORD" \
  -v dw_writer_password="$SJG_DW_WRITER_DB_PASSWORD" \
  -v dw_reader_password="$SJG_DW_READER_DB_PASSWORD" <<'SQL'
SELECT 'CREATE ROLE sjg_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_owner')\gexec
SELECT 'CREATE ROLE sjg_migration LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_migration')\gexec
SELECT 'CREATE ROLE sjg_api_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_api_runtime')\gexec
SELECT 'CREATE ROLE sjg_worker_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_worker_runtime')\gexec
SELECT 'CREATE ROLE sjg_audit_writer LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_audit_writer')\gexec
SELECT 'CREATE ROLE sjg_auditor LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_auditor')\gexec
SELECT 'CREATE ROLE sjg_dw_writer LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_dw_writer')\gexec
SELECT 'CREATE ROLE sjg_dw_reader LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_dw_reader')\gexec
SELECT 'CREATE ROLE sjg_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sjg_app')\gexec

ALTER ROLE sjg_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_migration LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_api_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_worker_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_audit_writer LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_auditor LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_dw_writer LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_dw_reader LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE sjg_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

SELECT format('ALTER ROLE sjg_migration PASSWORD %L', :'migration_password')\gexec
SELECT format('ALTER ROLE sjg_api_runtime PASSWORD %L', :'api_password')\gexec
SELECT format('ALTER ROLE sjg_worker_runtime PASSWORD %L', :'worker_password')\gexec
SELECT format('ALTER ROLE sjg_audit_writer PASSWORD %L', :'audit_writer_password')\gexec
SELECT format('ALTER ROLE sjg_auditor PASSWORD %L', :'auditor_password')\gexec
SELECT format('ALTER ROLE sjg_dw_writer PASSWORD %L', :'dw_writer_password')\gexec
SELECT format('ALTER ROLE sjg_dw_reader PASSWORD %L', :'dw_reader_password')\gexec

GRANT sjg_owner TO sjg_migration;
SQL
