-- GENERATED FROM APPROVED KNOWLEDGE BASE DDL. DO NOT EDIT THIS FILE DIRECTLY.
-- source_path: Knowledge Base/03 数据库需求规则/03_SQL_DDL/02_sjg_audit/02_audit_tables.sql
-- source_sha256: cdb16eb8ffe601a74a6d9b4764c0c81e3c5c3f95038996c8d9be35c7504a9304
SET ROLE sjg_owner;
-- Schema: audit / 审计治理
SET search_path TO audit, public;

-- 敏感访问日志: 敏感访问日志；只增不改，禁止业务服务直接UPDATE/DELETE
CREATE TABLE IF NOT EXISTS audit.access_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    actor_id uuid,
    resource_type varchar(128) NOT NULL,
    resource_id uuid,
    fields_accessed jsonb,
    purpose varchar(255),
    occurred_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE audit.access_log IS '敏感访问日志｜敏感访问日志；只增不改，禁止业务服务直接UPDATE/DELETE';
COMMENT ON COLUMN audit.access_log.id IS '日志ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.access_log.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.access_log.actor_id IS '访问人｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.access_log.resource_type IS '资源类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.access_log.resource_id IS '资源ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.access_log.fields_accessed IS '访问字段｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.access_log.purpose IS '访问用途｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.access_log.occurred_at IS '发生时间｜敏感级别:P1-内部';

-- 数据变更日志: 数据变更日志；只增不改，禁止业务服务直接UPDATE/DELETE
CREATE TABLE IF NOT EXISTS audit.data_change_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    table_name varchar(128) NOT NULL,
    record_id uuid NOT NULL,
    operation varchar(16) NOT NULL,
    before_data jsonb,
    after_data jsonb,
    changed_fields jsonb,
    occurred_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE audit.data_change_log IS '数据变更日志｜数据变更日志；只增不改，禁止业务服务直接UPDATE/DELETE';
COMMENT ON COLUMN audit.data_change_log.id IS '日志ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.table_name IS '表名｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.record_id IS '记录ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.operation IS '操作类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.before_data IS '变更前｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.after_data IS '变更后｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.changed_fields IS '变更字段｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.data_change_log.occurred_at IS '发生时间｜敏感级别:P1-内部';

-- 操作审计日志: 操作审计日志；只增不改，禁止业务服务直接UPDATE/DELETE
CREATE TABLE IF NOT EXISTS audit.operation_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    actor_id uuid,
    actor_identity_id uuid,
    action varchar(64) NOT NULL,
    resource_type varchar(128) NOT NULL,
    resource_id uuid,
    request_id varchar(128),
    occurred_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE audit.operation_log IS '操作审计日志｜操作审计日志；只增不改，禁止业务服务直接UPDATE/DELETE';
COMMENT ON COLUMN audit.operation_log.id IS '日志ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.actor_id IS '操作人ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.actor_identity_id IS '操作身份ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.action IS '动作｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.resource_type IS '资源类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.resource_id IS '资源ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.request_id IS '请求ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.operation_log.occurred_at IS '发生时间｜敏感级别:P1-内部';

-- 规则执行日志: 规则执行日志；只增不改，禁止业务服务直接UPDATE/DELETE
CREATE TABLE IF NOT EXISTS audit.rule_execution_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    rule_code varchar(64) NOT NULL,
    rule_version integer NOT NULL,
    business_key varchar(128),
    input_hash varchar(128),
    result varchar(32) NOT NULL,
    result_detail jsonb,
    occurred_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE audit.rule_execution_log IS '规则执行日志｜规则执行日志；只增不改，禁止业务服务直接UPDATE/DELETE';
COMMENT ON COLUMN audit.rule_execution_log.id IS '日志ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.rule_code IS '规则编码｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.rule_version IS '规则版本｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.business_key IS '业务键｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.input_hash IS '输入摘要｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.result IS '执行结果｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.result_detail IS '结果详情｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.rule_execution_log.occurred_at IS '发生时间｜敏感级别:P1-内部';

-- 安全事件日志: 安全事件日志；只增不改，禁止业务服务直接UPDATE/DELETE
CREATE TABLE IF NOT EXISTS audit.security_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    tenant_id uuid NOT NULL,
    event_type varchar(64) NOT NULL,
    severity varchar(16) NOT NULL,
    actor_id uuid,
    ip_address inet,
    device_fingerprint varchar(255),
    detail jsonb,
    occurred_at timestamptz DEFAULT now() NOT NULL
);
COMMENT ON TABLE audit.security_event IS '安全事件日志｜安全事件日志；只增不改，禁止业务服务直接UPDATE/DELETE';
COMMENT ON COLUMN audit.security_event.id IS '日志ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.tenant_id IS '租户ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.event_type IS '事件类型｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.severity IS '严重级别｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.actor_id IS '主体ID｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.ip_address IS 'IP地址｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.device_fingerprint IS '设备指纹｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.detail IS '详情｜敏感级别:P1-内部';
COMMENT ON COLUMN audit.security_event.occurred_at IS '发生时间｜敏感级别:P1-内部';
RESET ROLE;
