export type AuthzCapabilityType='VIEW'|'OPERATE'|'APPROVE'|'ADMIN'
export interface AuthzModuleView{id:string;moduleCode:string;moduleName:string;moduleGroup:string|null;parentId:string|null;processCodes:string[];sortNo:number;icon:string|null;enabled:boolean;remark:string|null;permissionCount:number}
export interface AuthzModuleCommand{moduleCode:string;moduleName:string;moduleGroup:string|null;parentId:string|null;processCodes:string[];sortNo:number;icon:string|null;enabled:boolean;remark:string|null}
export interface AuthzPermissionView{id:string;permissionCode:string;permissionName:string;actionCode:string;riskLevel:string;capabilityType:AuthzCapabilityType|null}
export interface AuthzPermissionSelection{permissionId:string;capabilityType:AuthzCapabilityType}
export interface AuthzOrgModuleView{moduleId:string;moduleCode:string;moduleName:string;moduleGroup:string|null;enabled:boolean;inheritToChildren:boolean;effectiveStartAt:string|null;effectiveEndAt:string|null;remark:string|null}
export interface AuthzOrgModuleSelection{moduleId:string;enabled:boolean;inheritToChildren:boolean;effectiveStartAt:string|null;effectiveEndAt:string|null;remark:string|null}
export interface AuthzRoleView{id:string;roleCode:string;roleName:string;roleType:string;dataScopeCode:string|null;enabled:boolean}
export interface AuthzPositionRoleView{roleId:string;roleCode:string;roleName:string;dataScopeCode:string|null;selected:boolean;effectiveStartAt:string|null;effectiveEndAt:string|null;grantSource:string|null}
export interface AuthzPositionRoleSelection{roleId:string;effectiveStartAt:string|null;effectiveEndAt:string|null;grantSource:string}
export interface AuthzOrganizationView{id:string;orgCode:string;orgName:string;orgType:string;parentId:string|null;path:string|null;status:string}
export interface AuthzPositionView{id:string;positionCode:string;positionName:string;orgId:string;status:string}
export interface AuthzReferenceData{organizations:AuthzOrganizationView[];positions:AuthzPositionView[];roles:AuthzRoleView[];permissions:AuthzPermissionView[]}
export interface AuthzRoleSource{roleId:string;roleCode:string;roleName:string;dataScopeCode:string|null;source:string}
export interface AuthzPermissionSimulation{permissionCode:string;permissionName:string;actionCode:string;riskLevel:string;capabilityType:AuthzCapabilityType|null;sourceRoles:string[];moduleCodes:string[];effective:boolean;reason:string}
export interface AuthzPreviewCommand{orgId:string;positionId:string;directRoleIds:string[];effectiveAt:string|null}
export interface AuthzPreviewResult{orgId:string;positionId:string;effectiveAt:string;roles:AuthzRoleSource[];enabledModules:AuthzModuleView[];permissions:AuthzPermissionSimulation[];effectivePermissionCodes:string[];filteredPermissionCodes:string[];dataScopes:string[];persisted:boolean}
export interface StepUpTicketResponse{ticket:string;purpose:string;requiredMfaLevel:number;expiresAt:string}
